Adjustments for enterprise widget
Graylog2/graylog2-server pull request #10036
Opened 2021-02-09 15:07 UTC by kmerz

## Motivation
Prior to this change, we handled the z-index for the sidebar in way that
it was hard to add new z-index for widgets.
Also we could not disable a icon button.

## Description
This change raise the z-index for the sidebar so widget have a little
space for their own z-index without jumping out of the overlay.
Add IconButton disable prop.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

2021-02-09 15:44 UTC, kyleknighted requested changes

2021-02-09 15:44 UTC, kyleknighted commented on graylog2-web-interface/src/components/common/IconButton.tsx
> +const Wrapper = styled.button(({ theme, disabled }: {theme: any, disabled: boolean}) => css`
I think `theme` is already defined in `src/@types/styled-components/index.d.ts`

2021-02-16 13:54 UTC, linuspahl approved these changes

2021-02-16 13:57 UTC, kyleknighted approved these changes

2021-02-16 13:58 UTC, merged