Return only summary of existing searches/dashboards
Graylog2/graylog2-server pull request #10280
Opened 2021-03-18 11:53 UTC by janheise

In places where only a subset and not all object's attributes is needed, only summaries of Searches and Dashboards are loaded and transferred between backend and frontend.

## Description
A new ViewSummaryDTO object is introduced that holds only a subset of the ViewDTO object's attributes. 
Also, a new ViewSummaryService i introduced and injected into the DashboardResource and SearchResource.
The requirements for View on the frontend-side have been loosened so that missing fields that had been required in the past are no longer necessary.

## Motivation and Context
Motivation is twofold:
1. when new fields are introduced to Views (e.g. feature branches) and documents with those fields exist in the db, loading those documents fail after switching to a different branch that does not hold those changes in structure.
2. the payload to transport those DTOs to the frontend is reduced as only the necessary attributes for displaying them are loaded from the db and serialized/deserialized

## How Has This Been Tested?
1. manually tested graylog after the changes that the functionality still works as expected in the GUI with valid objects
2. introduced invalid objects into MongoDB and tested again

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-04-09 12:00 UTC, dennisoelkers requested changes
Looks good, works well! Just a couple of minor nitpicks left.

2021-04-12 08:18 UTC, janheise commented on graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java
> +    public Set<String> getExpiredSearches(final Set<String> requiredIds, final Instant mustNotBeOlderThan) {
I vote for "neverDeleteIds"

2021-04-12 08:27 UTC, janheise commented on graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchSummaryRequirements.java
> +public class SearchSummaryRequirements extends Requirements<SearchSummary> {
You're correct, it should be obsolete now.

2021-04-12 10:05 UTC, dennisoelkers approved these changes
Looks good, works great! :tada:

2021-04-12 10:05 UTC, merged