Adaptable Dashboard Tabs
Graylog2/graylog2-server pull request #10371
Opened 2021-04-05 19:40 UTC by kyleknighted

## Description

Appends tabs to a Dropdown dependent on how wide the resolution is

## Motivation and Context

Too many tabs on a Dashboard leads to tabs wrapping to the next line and generally a poor experience and visual representation

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/122591/113618035-b8e1f980-961c-11eb-87ed-23b19ec2d53f.png)
![image](https://user-images.githubusercontent.com/122591/113618067-c1d2cb00-961c-11eb-9228-e48491c09efa.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-04-07 14:44 UTC, kmerz approved these changes
LGTM :+1: Worked on my machine.

2021-04-08 12:52 UTC, linuspahl reviewed
Code looks good to me and it works well, I like the new page title styling.

The only suggestion I have, let's display background color for the active page title. We could use the same background color for the three dots, if one of the hidden pages is active. I saw that we are already adjusting the dots color, but this way it is easier to understand that one of the hidden pages is active.

2021-04-08 12:52 UTC, linuspahl commented on graylog2-web-interface/src/views/components/QueryTabs.tsx
> +  let maxWidth = moreBtn.offsetWidth + newBtn.offsetWidth + 30; // magic number is PageContentLayout__Container padding
I looks like we do not need to consider the page content layout padding here.

2021-04-08 12:59 UTC, dennisoelkers requested changes
Testing it fails for me with this, when creating/opening a dashboard:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': 'li:not(.dropdown):not(.query-tabs-new):not(.dropdown-menu li)' is not a valid selector.
    at adjustTabs (http://localhost:8080/app.js:66888:32)
```

2021-04-08 14:03 UTC, dennisoelkers requested changes
I got it working on Firefox and tested it a little bit. It looks better, but it also requires a second click when going to a later tab. 

Important: When a tab is active, we should not hide its title. When a tab is selected from the ellipsis menu, the title is hidden right now.

2021-04-14 15:34 UTC, dennisoelkers requested changes
One remark regarding size calculation, also: can you write some tests for it?

2021-04-14 15:34 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/QueryTabs.tsx
> +    window.addEventListener('resize', throttle(adjustTabs, 250));
A potentially easier solution would also be to use the `SizeMe` component from `react-sizeme` instead, which could potentially also simplify the logic used to generate the tabs. At least we can hand off the size provisioning and handling of window resizes to it.

2021-05-04 10:08 UTC, linuspahl approved these changes
Looks good to me!

2021-05-12 08:43 UTC, kmerz commented
I tested the version again. And beside the known issues I could not see any problems. :heavy_check_mark:

2021-05-12 14:04 UTC, dennisoelkers approved these changes
Works greats and looks good now! Thanks for the patience of everyone involved! :heart:

2021-05-12 14:04 UTC, merged