Execute search only for focused widget
Graylog2/graylog2-server pull request #10426
Opened 2021-04-13 12:20 UTC by kmerz

## Motivation
Prior to this change, whenever a search was executed the search was
executed for all widgets, regardless if they are seen or not.

## Description
This change will add a SearchAction which sets a filter by which the
search types will be filtered before beeing send to the server.
This filter will be set from the widget focus provider when ever a
widget gets focused or edited.

## How Has This Been Tested?
- Set a widget into focus and execute a search
- Check the result via webconsole

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Fixes #10250

2021-04-13 12:48 UTC, dennisoelkers requested changes
Some nitpicking regarding names and types :)

2021-04-13 12:48 UTC, dennisoelkers commented on graylog2-web-interface/src/views/actions/SearchActions.ts
> +  setFilterSearchTypes: (FilterSearchTypes) => Promise<void>,
The parameter needs a name in TypeScript, it should be:
```suggestion
  setFilterSearchTypes: (searchTypes: FilterSearchTypes) => Promise<void>,
```

Without a variable name, it assigns an implicit `any` to the parameter. We can err out later, after we have enabled `noImplicitAny` in the TS config, but this requires some grunt work on our legacy code before.

2021-04-13 12:48 UTC, dennisoelkers commented on graylog2-web-interface/src/views/actions/SearchActions.ts
> +  setFilterSearchTypes: (FilterSearchTypes) => Promise<void>,
In my understanding the action name is misleading. While we are effectively filtering the executed search types at some point, the intention is to filter the search types of a _widget_ to be executed. The naming here implies that we need to pass _search type ids_, but judging from the code in `SearchStore`, we need to pass a list of _widget ids_ here.

2021-04-13 12:48 UTC, dennisoelkers commented on graylog2-web-interface/src/views/stores/SearchStore.ts
> +  filterSearchTypes: FilterSearchTypes | undefined | null;
Maybe we do want to limit this to `FilterSearchTypes | null`? `null` would be used if it should not be filtered at all. This way we could ensure that `undefined` is not passed accidentally due to a programmatic error here (e.g. an optional chain that is short-circuiting).

2021-04-15 07:54 UTC, linuspahl approved these changes
Looks good to me, could not find any problems.

2021-04-15 09:17 UTC, dennisoelkers approved these changes
Looks good, works well!

2021-04-15 09:17 UTC, merged