Add id filter to stream
Graylog2/graylog2-server pull request #10537
Opened 2021-04-30 12:46 UTC by kmerz

## Motivation and Context
The stream id is used all over the place when referencing a stream (e.g event message) but there is NO WAY
to find a stream based on its id.

## Description
Add a id filter option to the streams overview page.
Also add a Query Helper.

## How Has This Been Tested?
- search with `id: 5f4dfb9c69be46153b9a9a7b`

## Screenshots (if appropriate):
![Graylog - Streams (1)](https://user-images.githubusercontent.com/448763/116696881-c2b01000-a9c2-11eb-8136-80181a7a823d.png)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Note
Suggest a backport to 3.3

2021-05-04 15:10 UTC, linuspahl reviewed
What do you think about mentioning the id in the query helper info for (at least) the users and teams overview as well?

2021-05-10 14:22 UTC, bernd requested changes
Thank you! Can you please merge in the current master branch? There are some conflicts. Thank you!

2021-05-10 14:22 UTC, bernd commented on graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java
> +            case ID:
Can you please rename this to `OBJECT_ID` to make it a bit more explicit? :slightly_smiling_face: Thank you!

2021-05-19 16:15 UTC, bernd approved these changes
LGTM :+1:

2021-05-26 09:55 UTC, linuspahl requested changes
When a user searches for an id and there is no results, the search results in a bad request. For example: `id:search-id`. This is the case for every entity (saved searches, streams...).
It would be optimal if we keep the request result consistent, in comparision with other query fields.

2021-05-26 15:00 UTC, kmerz commented
> When a user searches for an id and there is no results, the search results in a bad request. For example: `id:search-id`. This is the case for every entity (saved searches, streams...).
> It would be optimal if we keep the request result consistent, in comparision with other query fields.

This is because the `id:search-id` is not a valid id and the response is a illegal argument. We should handle that better but this will not part of this release anymore. I will open a separate issue for that.

2021-05-26 15:07 UTC, linuspahl approved these changes

2021-05-26 15:07 UTC, merged