Use ColorMapper for event annotations
Graylog2/graylog2-server pull request #10593
Opened 2021-05-07 12:08 UTC by kmerz

## Motivation
Before the change the event annotaion color was not stable from the
beginning since it was not taking its color from the color mapper.

## Description
This PR will use the color mapper to add the color of the event
annotation.

Fixes #10340

## How Has This Been Tested?
- Create a histogram
- activate event annotation
- change the color of the event annotation

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-05-26 11:02 UTC, dennisoelkers requested changes
Looks good, works fine - just a single line that slipped in accidentally.

2021-05-26 11:02 UTC, dennisoelkers commented on graylog2-web-interface/package.json
> +    "test": "jest --maxWorkers=3",
This line slipped in :/

2021-05-27 12:18 UTC, linuspahl requested changes
It looks like the problem described in https://github.com/Graylog2/graylog2-server/issues/10340 still exists.

![Untitled](https://user-images.githubusercontent.com/46300478/119824570-57d8f280-bef6-11eb-8a91-3cf479202e36.gif)

2021-06-01 09:34 UTC, linuspahl commented
@kmerz While the chart colors no longer change when:
- e.g. metric has no custom color and user enables event annotations
They are still changing when:
- metric has a custom color and user enables event annotations

![event-annotations](https://user-images.githubusercontent.com/46300478/120301508-36e51880-c2cd-11eb-8610-c677bd5e0e31.gif)

2021-06-02 15:17 UTC, linuspahl approved these changes
Looks good to me! Could not find any errors. I thought it may results in a problem that we consider the old widget config when we submit the widget config form, but I could not find one.

2021-06-03 07:45 UTC, dennisoelkers approved these changes

2021-06-03 08:07 UTC, merged