Centralize reused margins in theme.
Graylog2/graylog2-server pull request #10676
Opened 2021-05-20 14:30 UTC by linuspahl

## Description

## Motivation and Context

This PR is creating a new section for the styled components theme called
margins. By centralizing the margins in the theme we can easily reuse them whenever we need to. It will
also make it easier to define margins and paddings relative to our commonly used margins.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-05-20 14:32 UTC, linuspahl commented on graylog2-web-interface/src/theme/margins.ts
> +export type Margins = {
Maybe you have a better name in mind than `margins`? I thought about others like `spacings` or `gabs`, but imo `margins` is more descriptive.

2021-05-20 15:28 UTC, kyleknighted requested changes
I like this concept! I think `Spacing` or `Gap` is probably a better name so that way we’re not setting padding from something called margins

Also, would like to assess some generated responsive spacing so that way we can have either something like “spacing-sm, spacing-med” etc
Or we could go Tailwind-esk with `spacing-N` and generate a number of sizes from minuscule to huge that can be used

I would also like to avoid defining `px` within the css and instead have the theme handle the scale.

2021-05-25 14:49 UTC, linuspahl commented on graylog2-web-interface/src/theme/margins.ts
> +export type Margins = {
I renamed the section to `spacings`.

2021-05-27 13:08 UTC, linuspahl commented
Closing in favour of https://github.com/Graylog2/graylog2-server/pull/10719

2021-05-27 13:08 UTC, closed without merging