Always apply all widget changes when saving aggregation builder.
Graylog2/graylog2-server pull request #10672
Opened 2021-05-19 12:33 UTC by linuspahl

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-05-21 07:58 UTC, linuspahl commented on graylog2-web-interface/src/views/components/contexts/WidgetEditApplyAllChangesProvider.tsx
> +      return WidgetActions.update(widget.id, newWidget)
When a user changes the widget and directly clicks on the "Apply changes" button we are currently executing the search twice. Do you have an idea what could be a good solution for this problem?

2021-06-02 09:49 UTC, dennisoelkers requested changes
The PR needs a rebase before I can test it properly. I added two smaller annotations inline, maybe it makes sense to address them (or not) together with the rebase?

2021-06-02 09:49 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
> +// jest.mock('views/components/contexts/WidgetEditApplyAllChangesProvider', () => ({ children }) => <WidgetEditApplyAllChangesContext.Provider></>);
I guess this line can be removed?

2021-06-02 10:08 UTC, linuspahl commented on graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
> +    const applyButton = await screen.findByRole('button', { name: 'Update Preview' });
Would you create one helper per file or one helper for all files?

2021-06-02 11:19 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
> +    const applyButton = await screen.findByRole('button', { name: 'Update Preview' });
Good question. Both ways have their pros/cons. I guess one helper per file is a good compromise between keeping tests decoupled and allowing to make changes easily.

2021-06-03 11:29 UTC, dennisoelkers approved these changes
Looks great now! :tada:

2021-06-03 11:30 UTC, merged