Use relative URLs for web interface assets served by Graylog server.
Graylog2/graylog2-server pull request #10726
Opened 2021-05-27 13:01 UTC by dennisoelkers

## Description

## Motivation and Context

Prior to this change, all web interface assets were qualified according from the following data points, in order of precedence:

 - The `X-Graylog-Server-URL` header of the request
 - The `http_external_uri` config setting
 - The `http_publish_uri` config setting

The result of this is used as the "effective external URI".

While this helps us supporting a couple of scenarios where the Graylog server is accessed through a reverse proxy, it also produces issues when naming schemes are different internally and externally and access from both directions is desired. The only scenario which works in these cases is configuring a valid `http_publish_uri`/`http_external_uri` for internal and using the `X-Graylog-Server-URL` on the proxy for external clients.

This is related to all of these settings being absolute URLs, resulting in generating absolute URLs for the web assets as well, unnecessarily.

In all of the cases this complexity of configuration would be unnecessary, if the references to the web assets would be relative. This would support all of the aforementioned use cases and does not rely on proper configuration of any of the settings _in order to be able to load the web assets properly_ if there is no additional path prefix.

Therefore, this PR is determining the effective external URI in the same way as listed before, but takes only the path part of it to prefix all web assets.

In a future PR, we could also apply a similar logic to the URL for the Graylog server API. We do assume that in most use cases the backend API URL is relative to the endpoint which served the web assets, so we could also provide a relative URL to it when bootstrapping the web interface, which would help us simplifying the http configuration for most scenarios while yielding a more reliable result when accessed internally as well as externally.

Fixes #10632.
Fixes #10267.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-05-28 11:34 UTC, kmerz reviewed
Code LGTM and the concept sounds solid. :+1: 
Need more time for testing though.

2021-06-02 15:54 UTC, bernd requested changes
Thanks for the PR! I like the idea of using relative URLs! :+1: 

Can you please check all usages of `RestTools#buildExternalUri`? It is used in other places like `AppConfigResource`, `DevelopmentIndexHtmlGenerator` and the documentation browser resources. I think we should return relative URLs there as well.

We can probably create a new method in `RestTools` that can be used in the different places.

2021-06-02 15:54 UTC, bernd commented on graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java
> +        final String path = externalUri.getPath() + (externalUri.getPath().endsWith("/") ? "" : "/");
`RestTools#buildExternalUri` already ensures a trailing `/` at the end of the URI. So think we can remove the check here.

2021-06-03 07:33 UTC, dennisoelkers commented
@bernd: Thanks for the great feedback!

> Can you please check all usages of RestTools#buildExternalUri? It is used in other places like AppConfigResource, DevelopmentIndexHtmlGenerator and the documentation browser resources. I think we should return relative URLs there as well.

> We can probably create a new method in RestTools that can be used in the different places.

I had already prepared a follow-up branch for this, using a relative URL for the backend (see 61b7fcf814a9ae79d99160ba20776b16fa5459e5) which is introducing a method like that. I just wanted to check first if the general idea is reasonable. What would you suggest on how to proceed? Integrate the two PRs? Or merge this one first and following up with the second afterwards?

2021-06-04 15:36 UTC, bernd commented
> @bernd: Thanks for the great feedback!
> 
> > Can you please check all usages of RestTools#buildExternalUri? It is used in other places like AppConfigResource, DevelopmentIndexHtmlGenerator and the documentation browser resources. I think we should return relative URLs there as well.
> 
> > We can probably create a new method in RestTools that can be used in the different places.
> 
> I had already prepared a follow-up branch for this, using a relative URL for the backend (see [61b7fcf](https://github.com/Graylog2/graylog2-server/commit/61b7fcf814a9ae79d99160ba20776b16fa5459e5)) which is introducing a method like that. I just wanted to check first if the general idea is reasonable. What would you suggest on how to proceed? Integrate the two PRs? Or merge this one first and following up with the second afterwards?

@dennisoelkers Oh sorry, I didn't notice the other branch. I think we can just do that in this PR. :slightly_smiling_face:

2021-06-07 16:52 UTC, bernd requested changes
One comment, apart from that it works fine! :+1:

2021-06-07 16:52 UTC, bernd commented on graylog2-server/src/main/java/org/graylog2/rest/RestTools.java
> +    public static URI buildRelativeExternalUri(@NotNull MultivaluedMap<String, String> httpHeaders, @NotNull URI defaultUri) {
Can we use this method for the following resources as well?

- DevelopmentIndexHtmlGenerator
- DocumentationResource
- DocumentationBrowserResource

2021-06-08 13:13 UTC, bernd approved these changes
Thanks for addressing the comments! :+1:

2021-06-08 13:14 UTC, merged