Implement generic OIDC login
Graylog2/graylog2-server pull request #10998
Opened 2021-07-08 10:00 UTC by patrickmann

This is the companion PR to https://github.com/Graylog2/graylog-plugin-enterprise/pull/2410 and https://github.com/Graylog2/graylog-plugin-cloud/pull/944

We introduce more generic naming and change visibility of `initial_graylog_roles` in support of increased inheritance and code re-use.

2021-07-26 15:51 UTC, thll commented
@patrickmann the diff appears to show many unrelated changes. could you rebase the PR to the current `master` please?

2021-07-26 15:59 UTC, thll commented
From the description: 

> /jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2410

I think we shouldn't have this dependency here. The build should pass without it, otherwise we'd have a problem for the non-enterprise version. Can we remove this?

2021-07-27 08:06 UTC, thll commented
> From the description:
> 
> > /jenkins-pr-deps [Graylog2/graylog-plugin-enterprise#2410](https://github.com/Graylog2/graylog-plugin-enterprise/pull/2410)
> 
> I think we shouldn't have this dependency here. The build should pass without it, otherwise we'd have a problem for the non-enterprise version. Can we remove this?

My bad, sorry for the noise. I was confusing this with the github actions build step which passes just fine. I added the Jenkins statement again.

2021-07-30 09:34 UTC, thll requested changes
As the backend code depending on this PR has been refactored, I think from a backend perspective this PR is now obsolete. We could keep the change in `AuthenticationDetails.java` though.

I didn't look at the UI changes.

2021-07-30 09:34 UTC, thll commented on graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackend.java
> +                                                                     boolean isExternal) {
Do we still need this change? I don't see it being used with the current state of the implementation so I vote for reverting it to keep the interface clean.

2021-07-30 09:34 UTC, thll commented on graylog2-server/src/main/java/org/graylog/security/authservice/AuthenticationDetails.java
> +    public abstract AuthenticationDetails.Builder toBuilder();
It's nice to have this, but we don't have code calling this. If we decide to keep the PR for the UI changes, we should leave this change in.

2021-08-09 09:27 UTC, thll approved these changes
Backend changes are fine.
Feel free to merge once the frontend changes have been reviewed.

2021-08-12 10:51 UTC, edmundoa commented on graylog2-web-interface/src/logic/authentication/okta/types.ts
> +  oktaBaseUrl?: string;
Should we change this types like we did in enterprise? That is, to have one for OIDC and one for Okta.

2021-08-12 16:16 UTC, edmundoa approved these changes
LGTM, thank you for all the work! 👍

2021-08-12 19:44 UTC, merged