Execute staled jobs.
Graylog2/graylog2-server pull request #11249
Opened 2021-09-07 12:16 UTC by AntonEbel

Locked jobs are now executed if the node no longer exists and a time threshold is exceeded.

## Motivation and Context

The current behavior of graylog is that only the node on which the job was running and not shut down properly can resolve the hanging job on the next startup. For each Graylog node, a node ID is generated at first startup and stored in a file on the file system. In a kubernetes environment old containers are discarded and new ones are created with new node IDs. So the hanging jobs are never resolved from the old nodes.

close #8612

Auto-unlock for scheduler triggers was already planned in this issue Graylog2/graylog-plugin-enterprise#1057 but with a different implementation.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-10-06 09:30 UTC, bernd requested changes

2021-10-06 09:30 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerConfiguration.java
> +    public static final String LOCK_EXPIRATION_TIME_MINUTES = "job_lock_expiration_time_minutes";
How about using the same prefix as the other option for consistency?
```suggestion
    public static final String LOCK_EXPIRATION_TIME_MINUTES = "job_scheduler_lock_expiration_time_minutes";
```

2021-11-03 17:42 UTC, thll approved these changes
LGTM and works. Nice work!

Handing over to @bernd to give the final OK.

2021-11-04 14:24 UTC, bernd approved these changes
Once @thll's https://github.com/Graylog2/graylog2-server/pull/11249#discussion_r742862251 is fixed, I am happy. :smile: 

Thanks a lot for working through all the feedback! :pray:

2021-11-15 09:49 UTC, thll approved these changes

2021-11-15 09:50 UTC, merged