Improve performance when comparing React elements
Graylog2/graylog2-server pull request #11252
Opened 2021-09-07 14:34 UTC by edmundoa

Performing deep equal comparisons of props may be expensive, specially when comparing React elements passed as children, and even more during development, since React elements will include additional debugging information that also needs to be compared. This caused tab freezes in the Pipeline Rules page, as described in #8657.

This PR changes the library used in `isDeepEqual.ts` to [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare), allowing us to do custom equality comparisons and improving performance when comparing React elements.

You can find performance profiles below but I thought it may be interesting to see a gist of them without all the hassle of loading them, so here are some captures of the critical moment. Before the change:
<img width="1645" alt="Screenshot 2021-09-07 at 15 58 00" src="https://user-images.githubusercontent.com/716185/132362361-87e086cd-4556-40b9-bbbe-5e99fe1a09da.png">

After the change:
<img width="1645" alt="Screenshot 2021-09-07 at 15 59 33" src="https://user-images.githubusercontent.com/716185/132362391-d825df77-b0f6-4584-bbf8-d009aaedfcf3.png">

<details>

<summary>Performance profiles</summary>

For reference, I uploaded some performance tests I captured on my browser with different comparison methods:
[new-pipeline-performance-comparison.zip](https://github.com/Graylog2/graylog2-server/files/7122264/new-pipeline-performance-comparison.zip)

- `new-pipeline-rule-lodash-only.json`: Compares elements using `lodash`, just as we did before
- `new-pipeline-rule-react-fast-compare-only.json`: Compares elements using `react-fast-compare`, as we do in this PR
- `new-pipeline-rule-lodash-and-react-fast-compare.json`: Mixes both approaches, using `react-fast-compare` only for React elements and `lodash` for any other comparison

The pipeline rules used during the performance tests are also included in the zip file.
</details>

Fixes #8657

2021-09-09 14:32 UTC, kyleknighted requested changes
Code looks great, is it possible to reduce the yarn.lock to only the changes needed for `react-fast-compare`? Unless @dennisoelkers thinks this is good, not sure the caveats of updating dependencies

2021-09-10 08:02 UTC, edmundoa commented
@kyleknighted I think the `yarn.lock` changes happen because it gets out of sync with changes and dependency updates from `package.json`. As far as I know, committing those changes would not have any effect on the packages installed by `yarn`, since the changes in `yarn.lock` also occur when running `yarn install` on a clean repository and will therefore also be included in a build.

2021-09-13 13:04 UTC, kyleknighted approved these changes

2021-09-14 11:04 UTC, dennisoelkers approved these changes
Looks good! Thanks a lot for this, @edmundoa!

2021-09-14 11:04 UTC, merged