Support for OpenSearch
Graylog2/graylog2-server pull request #11435
Opened 2021-10-07 12:23 UTC by todvora

## Description
This PR adds full support for OpenSearch in Graylog. Currently there logic and handling is similar to ES7, so the majority of the code changes solves dependency injections and search-server detection. 

## Motivation and Context
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2819

## How Has This Been Tested?
Full unit and integration tests run, locally manually tried to start and run the graylog server against opensearch instance. 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-11-03 11:25 UTC, janheise commented
docker-compose.yml used for my tests:
`version: "3"
 
services:
  mongodb:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
    volumes:
      - "mongoconfigdb:/data/configdb"
      - "mongodb:/data/db"
 
  opensearch:
    image: "opensearchproject/opensearch:1.1.0"
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - logger.deprecation.level=warn
      - action.auto_create_index=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - "opensearch:/usr/share/opensearch/data"
 
volumes:
  mongoconfigdb:
  mongodb:
  opensearch:
`

2021-11-03 11:27 UTC, janheise approved these changes
LGTM!

2021-11-03 16:21 UTC, todvora commented
Rebased and ready for a review from @dennisoelkers :pray:

2021-11-12 09:41 UTC, dennisoelkers requested changes
Looks good, just one minor remark.

2021-11-12 09:41 UTC, dennisoelkers commented on graylog2-server/src/main/java/org/graylog2/configuration/validators/ElasticsearchVersionValidator.java
> +        if (!SUPPORTED_ES_VERSIONS.contains(value.version())) {
We could also make `SUPPORTED_ES_VERSIONS` a `List<SearchVersion>` in order to keep the product<->version relationships. Then, at this line we could write the condition as 
```
if (SUPPORTED_ES_VERSIONS.stream().noneMatch(supportedVersion -> supportedVersion.satisfies(value.distribution(), value.version()))) {
```

2021-11-16 09:03 UTC, dennisoelkers approved these changes
Looks good! Let's get this moving!

2021-11-16 09:03 UTC, merged

2021-11-16 09:25 UTC, todvora commented
Thank you @dennisoelkers!

2022-03-02 13:59 UTC, bendem commented
It doesn't look like this is available in v4. Can this be backported to at least the maintained versions?