Enterprise issue 2124
Graylog2/graylog2-server pull request #11980
Opened 2022-01-18 12:53 UTC by ousmaneo

These changes extract `RolesTable.tsx` to its own component  and allow using exported RolesTable from enterprise plugin which display for role users that have inherited that role from a team assignment.

/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3070

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-01-21 13:36 UTC, patrickmann approved these changes
Tested with local and synced user / team. Looks good.

2022-02-15 10:54 UTC, edmundoa requested changes

2022-02-18 09:57 UTC, edmundoa approved these changes

2022-02-18 11:02 UTC, linuspahl approved these changes
Could not find any errors! Tested with and without plugins. I just added a suggestion.

2022-02-18 14:23 UTC, edmundoa commented on graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItemOverview.test.tsx
> +    expect(await screen.findByRole('button', { name: 'Delete' })).toBeInTheDocument();
Good find, I will take care of it. Thank you! 👍

2022-02-21 10:06 UTC, merged