Run validations for new URLs in allow list on first mount
Graylog2/graylog2-server pull request #12344
Opened 2022-03-23 12:28 UTC by edmundoa

2022-03-24 14:41 UTC, edmundoa commented on graylog2-web-interface/src/components/configurations/UrlWhiteListForm.tsx
>    }, [config]);
The linter failure here was left on purpose. Changing the dependency array had some negative consequences in the past, as well as increasing the number of calls to `onUpdate()` drastically, so I think changing it right now may do more harm than good before the release.

2022-03-28 08:34 UTC, ousmaneo approved these changes
Tested and works!

2022-03-28 08:48 UTC, ousmaneo requested changes
Thank you for the changes! I found a small issue on my last test (after approving). When I create a Regex URL and click save. It's still saved as `literal` and on edit too. it seems that the state of the URL type is not properly saved.

2022-03-29 08:22 UTC, ousmaneo approved these changes
Tested and works. Thank you for working on this 👍

2022-03-29 11:17 UTC, merged