Fix security tools placeholder route error
Graylog2/graylog2-server pull request #12475
Opened 2022-04-13 17:38 UTC by mikedklein

Fix for security page error when enterprise plugin isn't installed.

## Description

Addresses an error when the enterprise plugin isn't installed. When a user navigates to the security page without the enterprise plugin installed it will render correctly.

## Motivation and Context
Before this when a user went to the security page it would error because it was trying to use a link from the plugin routes. Now if the enterprise plugin isn't installed it falls back to link to the enterprise information page.

## How Has This Been Tested?

Tested locally with the enterprise plugin removed, enterprise plugin installed but no security license and with enterprise plugin installed with security license active.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-04-13 20:01 UTC, danotorrey requested changes
This tests successfully! Thanks for getting this in so quickly! 

I noticed one very small thing I am wondering if we can adjust:

There are two spaces on both sides of the "our product page" link instead of a single space (hard to see, but can be seen by selecting with the cursor). Is it possible to reduce that to a single space?

![image](https://user-images.githubusercontent.com/3423655/163259891-36a43383-0db8-4db1-a792-3036e8891bbf.png)
![image](https://user-images.githubusercontent.com/3423655/163259702-e8a1815e-ab92-43f7-b13a-06577d78fa14.png)

Note: Due to the master package issue, I was only able to test this by cherry-picking the commit over to a `4.3` checkout.

2022-04-14 20:21 UTC, danotorrey commented
I am finishing testing this now.

2022-04-14 20:40 UTC, danotorrey approved these changes
LGTM and tests successfully

Server only with no license or enterprise plugin:
![image](https://user-images.githubusercontent.com/3423655/163470748-21e5313d-9f9c-4c96-949e-2cae156a9b56.png)

Server with no license and enterprise plugins:
![image](https://user-images.githubusercontent.com/3423655/163471443-125fcb02-f7b3-4579-a273-29e3784431e5.png)

2022-04-15 13:00 UTC, kingzacko1 approved these changes

2022-04-15 13:49 UTC, merged