Limit size of system_messages collection
Graylog2/graylog2-server pull request #12540
Opened 2022-04-27 10:26 UTC by patrickmann

Mongo DB collection `system_messages` grows indefinitely. There is little point in storing years worth of old system messages. 
We now cap the size of collection, just as we do for e.g. `index_failures` collection.

Resolves Graylog2/graylog2-server#6118

2022-04-28 11:22 UTC, bernd commented
> **Note:** you cannot delete documents from a capped collection. Users will no longer be able trim the collection by deleting a subset of documents.

@patrickmann This needs an entry in the `UPGRADING.rst` to make sure users that upgrade are aware of it. Can you please ann an entry?

What's the reasoning behind using 5 MB for the capped collection? The `index_failures` collection is using 50 MB. I think 5 MB is quite small. What do you think?

2022-04-29 06:28 UTC, patrickmann commented
@bernd Bumped the cap to 50MB and added an entry in `UPGRADING.md`

2022-04-29 09:49 UTC, thll requested changes
The code looks good and works, but `UPGRADING.md` is still for version `4.3`. To make sure that your changes don't get lost, we should wait for #12570 to be merged and add your snippet then.

2022-04-29 11:14 UTC, thll approved these changes

2022-04-29 12:27 UTC, patrickmann commented
@boosty @bernd Only new customers will benefit from this (unless somebody manually drops the system messages collection so that it is recreated). I went with that approach, since other internal collections are also statically capped.
Is it worth doing this more flexibly via a scheduled job that periodically trims the collection?

2022-04-29 13:38 UTC, boosty commented
@patrickmann How about documenting how to convert an existing collection to a capped one?
https://www.mongodb.com/docs/manual/core/capped-collections/#convert-a-collection-to-capped

2022-05-02 07:31 UTC, merged