Prevent divide-by-zero exceptions in preflight checks
Graylog2/graylog2-server pull request #12821
Opened 2022-06-06 12:19 UTC by patrickmann

Avoid blocking preflight on divide-by-zero exceptions.
See #12820 for details.

2022-06-07 08:49 UTC, patrickmann commented
I think we need to backport to 4.3, as it has been reported multiple times already.

2022-06-07 09:43 UTC, mpfz0r commented
> I think we need to backport to 4.3, as it has been reported multiple times already.

yes, absolutely!

2022-06-08 14:49 UTC, mpfz0r requested changes
How about avoiding a division by zero here as well? just in case..

https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java#L76

2022-06-09 07:14 UTC, patrickmann commented
> How about avoiding a division by zero here as well? just in case..
> 
> https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java#L76

What should we use as default if we don't know the number of sockets? 1?

2022-06-09 10:53 UTC, mpfz0r approved these changes
LGTM :+1:

2022-06-09 10:54 UTC, mpfz0r commented
> What should we use as default for if we don't know the number of sockets? We could just set `totalSockets` to 1 in case it is 0 and let the other calculations proceed as is.

yeah, I think that's good enough

2022-06-09 10:54 UTC, merged