Configuring search filters for dashboard widgets/core
Graylog2/graylog2-server pull request #12835
Opened 2022-06-07 13:33 UTC by maxiadlovskii

## Description
Extend Widget, AggregationWidget, and MessageWidget to class to handle filters

## Motivation and Context
https://github.com/Graylog2/graylog-plugin-enterprise/issues/3647

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-06-10 14:03 UTC, linuspahl commented on graylog2-web-interface/src/views/logic/widgets/Widget.ts
> +      && isDeepEqual(this.filters, other.filters)
Let's use the same checks here for `fitler` and `filters` like in `Query.ts`, just to be save:
```
|| !((isNullish(this.filter) && isNullish(other.filter)) || isDeepEqual(this.filter, other.filter))
|| !((isNullish(this.filters) && isNullish(other.filters)) || isDeepEqual(this.filters, other.filters))
```

2022-06-16 15:22 UTC, dennisoelkers requested changes
Works well and looks good! Just added some minor comments for small cleanups.

2022-06-16 15:22 UTC, dennisoelkers commented on graylog2-web-interface/src/views/logic/widgets/MessagesWidget.ts
> +  constructor(id: string, config: any, filter: string | undefined | null, timerange: TimeRange | undefined | null, query: QueryString | undefined | null, streams: Array<string> = [], filters?: Filter
Afaics we do not rely on the default value for the `streams` parameter, so we can just remove it. This way we do not need to suppress `default-param-last` for the `filters` parameter.

2022-06-16 15:22 UTC, dennisoelkers commented on graylog2-web-interface/src/views/logic/widgets/Widget.ts
> +  constructor(id: string, type: string, config: any, filter?: string, timerange?: TimeRange, query?: QueryString, streams: Array<string> = [], filters?: FiltersType) {
Afaics we do not rely on the default value for the `streams` parameter, so we can just remove it. This way we do not need to suppress `default-param-last` for the `filters` parameter.

2022-06-16 15:22 UTC, dennisoelkers commented on graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidget.ts
> +  constructor(id: string, config: AggregationWidgetConfig, filter?: string, timerange?: TimeRange, query?: QueryString, streams: Array<string> = [], filters?: FiltersType) {
Afaics we do not rely on the default value for the `streams` parameter, so we can just remove it. This way we do not need to suppress `default-param-last` for the `filters` parameter.

2022-06-16 15:22 UTC, dennisoelkers commented on graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidget.ts
> +    // eslint-disable-next-line no-use-before-define,@typescript-eslint/no-use-before-define
The `typescript-eslint` hint should replace the previous one:

```suggestion
    // eslint-disable-next-line @typescript-eslint/no-use-before-define
```

2022-06-16 15:22 UTC, dennisoelkers commented on graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidget.ts
> +    // eslint-disable-next-line no-use-before-define,@typescript-eslint/no-use-before-define
Same here:

```suggestion
    // eslint-disable-next-line @typescript-eslint/no-use-before-define
```

2022-06-24 09:22 UTC, merged