Update SecurityPage when no Security license installed
Graylog2/graylog2-server pull request #12936
Opened 2022-06-22 20:41 UTC by kingzacko1

## Description

Make default Graylog Security page with no license installed more informative and less like an error page. See Graylog2/graylog-plugin-enterprise#3545 for context. 
## Motivation and Context

Closes Graylog2/graylog-plugin-enterprise#3545
## How Has This Been Tested?

Purely UI change of the SecurityPage. Tested functionality of links in refactored `EnterpriseProductLink` component
## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-06-22 23:34 UTC, mikedklein requested changes
I don't think the `vendor-modul-ids.json` should be in this PR right? 

The code all looks good minus the review bot suggestion and my other suggestion.

One content suggestion is to remove the graph.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/3578720/175174530-d4c8f16d-7c1c-4305-be80-1ea5c25d62cf.png">

Since that is kind of redundant. That being said I am not entirely sure what to put there.

2022-06-22 23:34 UTC, mikedklein commented on graylog2-web-interface/src/pages/SecurityPage.tsx
> +            Extend Graylog's capabilities for detecting, investigating, and responding to cybersecurity
Let's go with the review bot suggestion here it is technically a best practice albeit a nit.

2022-06-23 19:45 UTC, kingzacko1 commented
@mikedklein addressed your feedback and cleaned up bot suggestion. I'm open to any ideas about what else to put on that page instead of the traffic stuff.

2023-04-25 19:59 UTC, kingzacko1 commented
closing. This was handled in #15300

2023-04-25 19:59 UTC, closed without merging