Immutable Lookup Tables, Caches, and Data Adapters backend
Graylog2/graylog2-server pull request #13060
Opened 2022-07-15 12:45 UTC by ryan-carroll-graylog

Add immutable entities support for Lookup Tables, Caches, and Data Adapters.

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-07-18 20:23 UTC, roberto-graylog commented on graylog2-server/src/main/java/org/graylog2/lookup/db/DBCacheService.java
> +    // TODO: rename this or get rid of it. Same name (db) as superclass.
Yes, remove.

2022-07-18 20:27 UTC, roberto-graylog commented on graylog2-server/src/main/java/org/graylog2/lookup/db/DBLookupTableService.java
> +        int numDeleted = super.delete(idOrName);
While this is old code, relying on an exception as test (ID or name) is not a good approach.  In this case, we can use ObjectId to test whether idOrName is a valid ObjectId, if so, search by ID, else by name.

2022-07-19 21:04 UTC, roberto-graylog requested changes
This looks good to me.  It just needs the latest changes from `core_scoped_db_entities` for a final test.

2022-07-20 16:04 UTC, roberto-graylog approved these changes
Looks good to me.

2022-07-20 16:13 UTC, ryan-carroll-graylog commented
> Looks good to me.

Thanks for all the feedback.

2022-07-28 19:51 UTC, roberto-graylog approved these changes

2022-07-28 20:15 UTC, danotorrey requested changes
@ryan-carroll-graylog This LGTM and tests successfully! There is only one small method override that needs to be added in order for the Illuminate installation to automatically inject the scope:

This method override will need to added to all of the facades, so that the injector below will know which entity facades the `ILLUMINATE` scope can be injected for:
```
@Override
    public boolean usesScopedEntities() {
        return true;
    }
```

https://github.com/Graylog2/graylog-plugin-enterprise/blob/923d2d3dbdfde70d7bffd987ea32a1cb84ff7afb/enterprise/src/main/java/org/graylog/plugins/illuminate/installation/ContentPackScopeInjector.java#L46-L50

2022-07-28 20:32 UTC, ryan-carroll-graylog commented
> @ryan-carroll-graylog This LGTM and tests successfully! There is only one small method override that needs to be added in order for the Illuminate installation to automatically inject the scope:
> 
> This method override will need to added to all of the facades, so that the injector below will know which entity facades the `ILLUMINATE` scope can be injected for. Without this, the `DEFAULT` scope is used for Illuminate-installed content packs.
> 
> ```
> @Override
>     public boolean usesScopedEntities() {
>         return true;
>     }
> ```
> 
> https://github.com/Graylog2/graylog-plugin-enterprise/blob/923d2d3dbdfde70d7bffd987ea32a1cb84ff7afb/enterprise/src/main/java/org/graylog/plugins/illuminate/installation/ContentPackScopeInjector.java#L46-L50

@danotorrey I was just looking at this. Do these LUT entities need this even though they'll be installed outside the Illuminate content-pack pipeline, in the new code for @kingzacko1 changes?

I suppose it's probably good form to have it anyway for consistency in case we decide to use this elsewhere.

2022-07-29 17:53 UTC, ryan-carroll-graylog commented
> > @ryan-carroll-graylog This LGTM and tests successfully! There is only one small method override that needs to be added in order for the Illuminate installation to automatically inject the scope:
> > This method override will need to added to all of the facades, so that the injector below will know which entity facades the `ILLUMINATE` scope can be injected for. Without this, the `DEFAULT` scope is used for Illuminate-installed content packs.
> > ```
> > @Override
> >     public boolean usesScopedEntities() {
> >         return true;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/Graylog2/graylog-plugin-enterprise/blob/923d2d3dbdfde70d7bffd987ea32a1cb84ff7afb/enterprise/src/main/java/org/graylog/plugins/illuminate/installation/ContentPackScopeInjector.java#L46-L50
> 
> @danotorrey I was just looking at this. Do these LUT entities need this even though they'll be installed outside the Illuminate content-pack pipeline, in the new code for @kingzacko1 changes?
> 
> I suppose it's probably good form to have it anyway for consistency in case we decide to use this elsewhere.

Just added the overrides of usesScopedEntities() in the facades.

2022-07-29 18:50 UTC, kingzacko1 approved these changes
LGTM

2022-07-29 20:24 UTC, danotorrey commented
> I was just looking at this. Do these LUT entities need this even though they'll be installed outside the Illuminate content-pack pipeline, in the new code for @kingzacko1 changes?

@ryan-carroll-graylog Thanks @ryan-carroll-graylog Good point, sorry, I had gotten confused about this for a bit there. You are correct about that. They are not strictly needed. I agree though, adding them anyhow just in case sounds good to me.

2022-07-29 20:24 UTC, danotorrey approved these changes

2022-08-23 20:14 UTC, merged