skip index rotation on empty index
Graylog2/graylog2-server pull request #13099
Opened 2022-07-21 12:04 UTC by kodjo-anipah

## Description

/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3869
When using the Index Time rotation strategy, we should add an option to skip rotation when the index set contains 0 messages.

## Motivation and Context

Especially with Illuminate we see a lot of index sets being created, but not all of them might be used. When using a time based rotation (e.g. daily), this can lead to huge number of empty indexes / shards being created, which require system resources.
fixes #13028 
The Index Message Count and Index Size rotation strategies naturally do not have this problem.
## How Has This Been Tested?

Locally by configuring time based rotation for an index set
Case 1. There are messages in any index of the index sets, hence rotation is performed
Case 2. There are no messages in the whole index set, hence rotation is skipped 
Case 3. if rotateEmptyIndexSets is enabled, behaviour stays as before

## Screenshots (if appropriate):

![Screenshot 2022-07-26 at 15 04 57](https://user-images.githubusercontent.com/92227/181013090-fdfdb24d-df9b-4b45-8d9a-81b3393b45e7.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

2022-07-22 07:22 UTC, boosty commented
Hi @kodjo-anipah, thanks for working on this!

A few points from my side:
1. Is it safe to skip the rotation by just checking the number of messages in the current index? When I wrote https://github.com/Graylog2/graylog2-server/issues/13028, I suggested to only skip when the whole index set is empty, to not confuse the _retention_. This is because the retention is currently based on index count, so it cannot deal with randomly missing indexes within an index set. 
2. I think we should turn on this new option by default. I cannot think about a good reason for why one might want to rotate an unused index set.

2022-07-26 14:02 UTC, boosty commented on graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
> +                 label="Rotate empty index sets"
```suggestion
                 label="Rotate empty index set"
```

2022-07-26 14:02 UTC, boosty commented on graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
> +                 help="Apply the rotation strategy on empty index sets." />
```suggestion
                 help="Apply the rotation strategy even when all indexes are empty (not recommended)." />
```

2022-07-27 10:10 UTC, boosty commented on graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
> +                 help="Apply the rotation strategy even when all indexes are empty (not recommended)." />
```suggestion
                 help="Apply the rotation strategy even when the index set is empty (not recommended)." />
```

Sorry for this new suggestion again, but after reading my previous one again, I think this one fits much better.

2022-07-28 08:17 UTC, gally47 approved these changes
Frontend LGTM!

2022-07-29 07:51 UTC, boosty commented
What is the default value for this config option? As we are not recommending to rotate empty index sets, the option should be disabled by default.

2022-07-29 08:00 UTC, kodjo-anipah commented
> What is the default value for this config option? As we are not recommending to rotate empty index sets, the option should be disabled by default.

Default value is set to false and rotation on empty index sets are disabled.

2022-07-29 13:14 UTC, mpfz0r requested changes
A few comments

2022-07-29 13:14 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java
> +    public static final String ELASTICSEARCH_MAX_WRITE_INDEX_AGE_OVERRIDES_CONFIGURED_PERIOD = "(elasticsearch_max_write_index_age overrides configured period)";
Could we give this constant a shorter name?
How about `OVERRIDE_HINT`

2022-08-01 09:30 UTC, mpfz0r approved these changes

2022-08-01 09:31 UTC, merged