Allow to debug() an entire message in pipeline rules
Graylog2/graylog2-server pull request #13178
Opened 2022-08-02 13:20 UTC by mpfz0r

Make the argument to debug() optional.
If no argument is supplied, log the entire message in its current state.

2022-08-02 13:24 UTC, mpfz0r commented
See https://github.com/Graylog2/graylog2-server/issues/13043#issuecomment-1183252047

2022-08-04 08:52 UTC, moesterheld requested changes

2022-08-04 08:52 UTC, moesterheld commented on graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/debug.txt
> +    debug("message converted with to_string: " + to_string($message));
this debug call isn't verified, is it?

2022-08-04 10:25 UTC, mpfz0r commented on graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/debug.txt
> +    debug("message converted with to_string: " + to_string($message));
@moesterheld thanks :+1: fixed

2022-08-04 13:03 UTC, moesterheld approved these changes
Looks good.

2022-08-04 13:03 UTC, merged