Assign roles without using the submit button on user create page
Graylog2/graylog2-server pull request #13277
Opened 2022-08-23 10:54 UTC by grotlue

## Description
On the user creation page one can add and remove roles. 
This PR will remove the "Assign role" button from this view and assign roles when they are selected instead.

## Motivation and Context
When creating user the actual user creation does only happen when submitting the whole form, so there is no need for an additional button and thus step when adding or removing roles.

Closes https://github.com/Graylog2/graylog2-server/issues/9933

## How Has This Been Tested?
Environment: Local

- Created a new user, selected and deselected roles.
- Checked the new user after creation

✅ Roles were saved accordingly

## Screenshots (if appropriate):
**Before:**
![Monosnap screencast 2022-08-23 12-48-31](https://user-images.githubusercontent.com/3169354/186139853-179c0b2b-2e80-481e-aa97-4d332ee4966f.gif)

**After:*
![Monosnap screencast 2022-08-23 12-51-42](https://user-images.githubusercontent.com/3169354/186140496-211d8c36-1581-40d9-b40b-526e8f117174.gif)
*

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-08-24 10:49 UTC, mnin approved these changes
LGTM

2022-08-24 11:57 UTC, ousmaneo requested changes
Thank you for the changes this looks good to me. I added a small comment inline

2022-08-24 11:57 UTC, ousmaneo commented on graylog2-web-interface/src/components/permissions/RolesSelector.tsx
> +  const selectedRoleNamess = selectedRoleNames.split(',');
We should call this `selectedRolesNameArray` for example to make it more readable.

2022-08-26 09:50 UTC, ousmaneo approved these changes
LGTM!

2022-08-29 15:08 UTC, merged