Replace usage of `CurrentUserStore` with `useCurrentUser`.
Graylog2/graylog2-server pull request #13285
Opened 2022-08-24 09:48 UTC by linuspahl

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-08-31 13:47 UTC, dennisoelkers requested changes
Looks good! Just a couple of minor suggestions inline.

2022-08-31 13:47 UTC, dennisoelkers commented on graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.tsx
> +    asMock(useCurrentUser).mockReturnValue({} as User);
What about providing a valid user, but with undefined preferences instead?

2022-08-31 13:47 UTC, dennisoelkers commented on graylog2-web-interface/src/pages/StreamEditPage.tsx
> +const StreamEditPage = ({ params, location }) => {
Can you please type the props here?

2022-08-31 13:47 UTC, dennisoelkers commented on graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.tsx
> +    asMock(useCurrentUser).mockReturnValue(adminUser);
I think we can remove this and leave it to the default mock.

2022-08-31 13:47 UTC, dennisoelkers commented on graylog2-web-interface/src/pages/EditEventDefinitionPage.test.tsx
> +    asMock(useCurrentUser).mockReturnValue(adminUser);
I think we can remove this and leave it to the default mock.

2022-08-31 13:47 UTC, dennisoelkers commented on graylog2-web-interface/src/pages/ViewEventDefinitionPage.test.tsx
> +    asMock(useCurrentUser).mockReturnValue(adminUser);
I think we can remove this and leave it to the default mock.

2022-08-31 13:47 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/contexts/SearchPagePreferencesProvider.test.tsx
> +    asMock(useCurrentUser).mockReturnValue(adminUser);
I think we can remove this and leave it to the default mock.

2022-08-31 13:54 UTC, linuspahl commented
@dennisoelkers Regarding the usage of `asMock(useCurrentUser).mockReturnValue(adminUser);` in `beforeEach`, I am doing this whenever we are mocking the return value in one or more test cases, to ensure we reset the return value for all following test cases.

2022-08-31 14:09 UTC, dennisoelkers commented
@linuspahl: I understand the reasoning, but I think it is not needed in at least a couple of test suites, where we can remove them for now. The benefit is that we have a single mock implementation which we can maintain centrally.

2022-09-01 14:51 UTC, dennisoelkers approved these changes

2022-09-01 14:51 UTC, merged