Remove backend legacy alerting code
Graylog2/graylog2-server pull request #13420
Opened 2022-09-12 05:30 UTC by patrickmann

2022-09-15 10:35 UTC, mpfz0r reviewed
I left some comments.

We could mark a few things as `@Depreacted` e.g. the alerting stuff in `StreamDTO` 

Also,we should have a comment in `UPGRADING.md` about this.
e.g. that old alerts from content packs will simply be ignored from now on.

2022-09-15 11:52 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStats.java
> -                                      AlarmStats alarmStats) {
The `AlarmStats` class can also be deleted

2022-09-15 12:20 UTC, mpfz0r requested changes
Also `Stream` and `StreamImpl` has still `getAlertReceivers()` which can go away

2022-09-19 08:41 UTC, patrickmann commented on graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
> -        return configuration.isEnableLegacyAlerts();
The entire AlertScannerThread class is deleted.

2022-09-19 13:22 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
> -        return configuration.isEnableLegacyAlerts();
I've meant to delete `configuration.isEnableLegacyAlerts()`

2022-09-20 05:37 UTC, patrickmann commented on graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
> -        return configuration.isEnableLegacyAlerts();
Got it - removed that

2022-09-21 10:22 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
> -        return configuration.isEnableLegacyAlerts();
there's more:
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/Configuration.java#L149-L151

2022-09-22 13:45 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
> -        return configuration.isEnableLegacyAlerts();
@patrickmann ping ^^ :)

2022-09-23 06:42 UTC, patrickmann commented on graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
> -        return configuration.isEnableLegacyAlerts();
Good catch

2022-09-29 15:28 UTC, mpfz0r approved these changes
LGTM :+1:

2022-09-29 15:28 UTC, merged