Pass through error message from lookup
Graylog2/graylog2-server pull request #13508
Opened 2022-09-21 09:54 UTC by patrickmann

Handle error message from lookup for Graylog2/graylog-plugin-cloud#1046

2022-10-04 15:54 UTC, AntonEbel requested changes

2022-10-05 07:20 UTC, patrickmann commented on graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
> +    public static final String LOOKUP_KEY = "key";
I use the constant here:
https://github.com/Graylog2/graylog2-server/blob/91dd970e67d22e76a8effd0adc8f733b4dcf0473/graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java#L107

Matter of preference, but I prefer using a constant for strings defined in code.

2022-10-05 08:10 UTC, AntonEbel commented on graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
> +    public static final String LOOKUP_KEY = "key";
Sorry for the misunderstanding, I didn't mean the constant itself, but the `key` stored in `multiValue` in `LookupResult` or in `results` in `OTXLookupResult`. My point was that the `message` already contains the `key` information and is displayed in the UI and the key is somehow duplicate information.

2022-10-11 13:26 UTC, AntonEbel approved these changes
LGTM.

2022-10-14 06:07 UTC, merged