Invalidate registration cache only for affected sidecars
Graylog2/graylog2-server pull request #13514
Opened 2022-09-21 13:03 UTC by thll

When a configuration is saved, and its tags have changed, we used to invalidate the registration cache for all sidecars.

We now check which sidecars are potentially affected by the change by looking at their tags, and invalidate the cache only for those.

There is still the case where a change to the tags of a configuration don't result in a change of the assignment. In that case we wouldn't need to invalidate the cache. But in favor of keeping things simple, we don't try to prevent this.

2022-09-21 15:10 UTC, thll commented
Needs adjustment after https://github.com/Graylog2/graylog2-server/pull/13504

2022-09-22 07:57 UTC, mpfz0r requested changes
we could add this optimization also to `createConfiguration()`

2022-09-22 08:17 UTC, mpfz0r commented
other than that looks great :+1:

2022-09-22 13:36 UTC, mpfz0r approved these changes

2022-09-22 13:37 UTC, merged