Conceptual skeleton of possible solution of Simple Scripting API task
Graylog2/graylog2-server pull request #13809
Opened 2022-10-27 12:57 UTC by luk-kaminski

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-11-09 07:54 UTC, dennisoelkers requested changes
Looks good in general, added some suggestions for improvements inline.

2022-11-09 07:54 UTC, dennisoelkers commented on graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/SearchRequestSpecToSearchMapper.java
> +        search.addStreamsToQueriesWithoutStreams(() -> Set.of(Stream.DEFAULT_STREAM_ID));
What is the reason for using the default stream here for queries without streams? I think we should instead use all of the streams the user has access to, similar to how we do it in other place. At this point we also do not know if the user has even access to the default stream.

2022-11-09 07:54 UTC, dennisoelkers commented on graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java
> +                return Response.ok(tabularResponse).build();
We can just return `tabularResponse` in here, that makes it a bit easier to understand from the method signature what's returned. Below, we can throw a `NotFoundException`.

2022-11-09 07:54 UTC, dennisoelkers commented on graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/SearchRequestSpec.java
> +        if (timerange == null) {
Can we do the same for `streams` and assign an empty collection if it is missing? That also makes handling it later easier.

2022-11-09 07:54 UTC, dennisoelkers commented on graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/SearchRequestSpec.java
> +                                @JsonProperty("streams") List<String> streams,
Is there a reason for this to be a `List` instead of a `Set`?

2022-11-09 08:35 UTC, luk-kaminski commented
> Looks good in general, added some suggestions for improvements inline.

Thank you for your feedback, I'll soon push the changes. :)

2022-11-18 12:27 UTC, dennisoelkers approved these changes

2022-11-18 13:04 UTC, merged