Fix Clone Action of Configuration is out of place
Graylog2/graylog2-server pull request #13899
Opened 2022-11-07 17:40 UTC by gally47

## Motivation and Context

#13874

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-11-15 15:57 UTC, ousmaneo requested changes
Looks good, I think we can take the chance to move the file to `Typescript`.

2022-11-15 16:00 UTC, ousmaneo commented on changelog/unreleased/issue-13874.toml
> +message = "Fix Clone Action of Configuration is out of place"
```suggestion
message = "Fix Clone Action style on Collectors configurations list "
```

2022-11-23 15:00 UTC, mnin approved these changes
LGTM

2022-11-24 15:39 UTC, mnin approved these changes
LGTM

please use `git merge` instead of `git rebase` after first review was started, to give the reviewer to track the newest changes

2022-11-25 14:17 UTC, gally47 commented
> Looks good, I think we can take the chance to move the file to `Typescript`.

@ousmaneo is on vacation but he originally requested changes. @mnin reviewed the requested changes and approved them. So, I'll (try to) dismiss @ousmaneo 's review as I addressed the comments, so I can merge this PR. Leaving this comment here to clarify why I dismiss a review.

2022-12-01 09:50 UTC, dennisoelkers approved these changes

2022-12-01 09:50 UTC, merged