Use PKCS5Padding instead of ISO10126d2Padding for secrets encryption
Graylog2/graylog2-server pull request #14193
Opened 2022-12-12 18:42 UTC by mpfz0r

If Graylog is run in an FIPS environment there is no crypto provider available that supports "AES/CBC/ISO10126d2Padding". This is likely because this padding standard was withdrawn from ISO in 2007.
It is considered bad practice to leave a subliminal channel in the padding.

We tried to workaround this by explicitly using BouncyCastle for the encryption/decryption.

This however creates problems with Oracle Java, because we strip the signature off the bouncy castle jar while repackaging it into our Uber-Jar.
In contrast to OpenJDK, Oracle Java does not allow the use of unsigned Security Providers.

Solution:

Change our secret encryption to using PKCS5Padding instead. There is a FIPS compatible provider "SunPKCS11-NSS-FIPS" available which supports "AES/CBC/PKCS5Padding".

For backwards compatibility, we decrypt the ISO10126d2Padded keys without stripping the padding, and do that manually.

Fixes #14153

Refs #13525

2022-12-13 09:45 UTC, bernd approved these changes
Great work, thank you! :pray: 

I tested this with a 4.3 setup and LDAP. Without this change, I created the LDAP settings (and thus an encrypted value). Then I updated to a 4.3 that has this change applied. Everything worked.

2022-12-13 10:14 UTC, bernd commented
I also tested on a FIPS-enabled RedHat.

2022-12-13 14:41 UTC, bernd requested changes

2022-12-13 14:41 UTC, bernd commented on changelog/unreleased/issue-14153.toml
> +message = "Use PKCS5 instead of ISO10126 padding for secrets encryption"
This is quite cryptic for regular users. How about something like "Improve JVM security provider compatibility by switching to a widely supported cipher transformation."

2022-12-13 20:20 UTC, thll approved these changes
Looks good. Pending the one comment from @bernd, I think this is good to go.

Tested with RHEL 9 with fips mode disabled and also enabled. I was able to reproduce the issue with Oracle JDK 17 and Graylog version 5.0 and could observe the error being fixed when using the snapshot build for this PR. Reading encrypted values which have been written with Graylog version 5.0 worked flawlessly after the fix was applied.

2022-12-14 09:37 UTC, bernd approved these changes

2022-12-14 09:39 UTC, merged

2022-12-14 09:39 UTC, mpfz0r commented
5.0.1 backport: https://github.com/Graylog2/graylog2-server/pull/14211
4.3.9 backport: https://github.com/Graylog2/graylog2-server/pull/14212

2022-12-14 14:56 UTC, boosty commented
Thanks @mpfz0r for fixing, and @bernd and @thll for testing. Great work!