Simplify ULID creation
Graylog2/graylog2-server pull request #14340
Opened 2023-01-02 15:34 UTC by mpfz0r

Use 32 bits instead of 16 bits for storing the sequence number. This still leaves 48 bits of randomness in the ULID. 48 bits is still plenty of randomness to create unique ULIDs. Considering that we only need them uniqe per timestamp and ES index.

With 32 bits we can store the seq as an unsigned int and don't have to worry on how to shrink it down.
This simplifies the code a lot.

2023-01-09 17:09 UTC, thll requested changes
Great reduction of complexity! Works well 👍 

Just an observation: we don't handle wrapping of the sequence number. Is this on purpose for the sake of simplicity? Given that we can't guarantee strict sorting across inputs anyways, I think the rare chance of getting the order wrong within a millisecond due to sequence wrapping is negligible. (I think it'll be once a day at an ingest rate of ~ 50.000 msg/s on a single input)

2023-01-09 17:44 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/MessageULIDGenerator.java
> +        final long msbWithoutRandom = timestamp << 16;
good catch. let's add that check back :+1:

2023-01-09 17:48 UTC, mpfz0r commented
> Great reduction of complexity! Works well +1
> 
> Just an observation: we don't handle wrapping of the sequence number. Is this on purpose for the sake of simplicity? Given that we can't guarantee strict sorting across inputs anyways, I think the rare chance of getting the order wrong within a millisecond due to sequence wrapping is negligible. (I think it'll be once a day at an ingest rate of ~ 50.000 msg/s on a single input)

Yeah, that's expected. I wouldn't know how to handle that properly. Is there even a way?

2023-01-10 07:16 UTC, thll approved these changes

2023-01-10 07:16 UTC, merged