Sidecar Failure Tracking View
Graylog2/graylog2-server pull request #14435
Opened 2023-01-13 11:57 UTC by gally47

Sidecar Failure Tracking View that displays statuses, error messages, and verbose messages.

## Motivation and Context

fixes https://github.com/Graylog2/collector-sidecar/issues/433

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-02-06 16:53 UTC, grotlue requested changes
General approach looks good, but I have a few suggestions for changes.

I haven't tested it yet, will take some time for that tomorrow :)

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +        <colgroup>
Nice!

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +            {Object.keys(sidecarCollection).map((sort_key) => (
```suggestion
            {Object.keys(columns).map((columnKey) => (
```

Let's stick to camelcase and related to my suggestions above I'd rename it.

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +    const sidecarCollection = {
In this case, I find the naming confusing. 
```suggestion
    const columns = {
```

or maybe `columnsMap`

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +                {['node_name', 'last_seen'].includes(sort_key) && (
What about putting those into a const:
```
const sortableColumns = ['node_name', 'last_seen'];
```

```suggestion
                {sortableColumns.includes(sort_key) && (
```

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +  const formatNoMatchingListAlert = () => {
This method is not receiving anything that it's formatting. What about changing it to a component and renaming it:

```suggestion
  const NoMatchingListAlert = () => {
```

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +  const formatSidecarList = (sidecarRows: React.ReactNode[]) => {
What about naming this function after what it returns? We could also change it to a component:
```suggestion
  const SidecarTable = ({rows} : {rows: : React.ReactNode[]}) => {
```

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +            {sidecarList}
I would move the render logic in here, it is easier to read:
```suggestion
            {sidecarRows.length > 0 ? <SidecarTable rows={sidecarRows} /> : <EmptyList />}
```

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
> +  const renderEmptyList = () => {
Again, could be changed to a comp:

```suggestion
  const EmptyList = () => {
```

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingRows.tsx
> +    sidecarStatus = {
I am wondering if it would be nicer to use an effect hook here instead of a let. WDYT?

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingRows.tsx
> +  const renderSidecarCollectorRows = () => {
This could be moved directly into the return at the bottom. Reads nicer and saves a function call.

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingRows.tsx
> +    return sidecar.node_details.status.collectors.filter((collector) => collector.status === 2).map((collector) => {
Would be easier to read when putting the filtered collection into a variable, e.g. `failedSidecars` or something similar.

2023-02-06 16:53 UTC, grotlue commented on graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.test.tsx
> +    fireEvent.change(pageSizeInput, { target: { value: 100 } });
I think I would create own tests for each handler, this way when a test fails it's easier to understand which functionality failed just by the test description.

2023-02-07 15:52 UTC, grotlue commented
I tested it locally and everything except for one point seem to work fine:

https://user-images.githubusercontent.com/3169354/217294075-526d6c4f-c568-4bad-b4e1-53436940481b.mp4

https://user-images.githubusercontent.com/3169354/217294083-faf99c44-a120-41cf-ab50-142d526c5db6.mp4

- ✅ Page is showing a list of failed sidecars
- ✅ Search is working including search syntax and reset button
- ✅ List is sortable by name and last seen
- ✅ Click on the sidecar name leads to the sidecar detail page
  - ✅ Detail modal of the error messages still works on that page as well
- ✅ Error messages are scrollable
  - ✅ Click on more will open the error message in a modal
- ✅ Results are paginated correctly
- ✅ Inactive sidecars are hidden when clicking on "Hide Inactive Sidecars" button
- ❌ When the search has no results the text doesn't show the filter correctly
![Screenshot 2023-02-07 at 16 51 42](https://user-images.githubusercontent.com/3169354/217294514-e0f63bf6-7263-4927-ae61-22a99f27c409.png)

2023-02-16 09:55 UTC, grotlue requested changes
Code-wise it looks good now, thanks for all the changes!

While testing I saw that the issue with the text for a search without results still exists:
![Screenshot 2023-02-16 at 10 49 28](https://user-images.githubusercontent.com/3169354/219331350-1429a6e5-39b7-463d-8f09-d12f9c7a6274.png)

Besides that I tested the following other features which all work as expected:
- Pagination (3 pages, also checking different page size)
- Filtering
- Sort
- Opening the error message
- Link to detail view

2023-02-16 10:24 UTC, ousmaneo commented
Thank you for testing and reviewing. I fixed the issue.

2023-02-16 10:50 UTC, grotlue approved these changes
The build is failing, but it's only due to unused vars. I check it and it looks good now!

![Screenshot 2023-02-16 at 11 34 14](https://user-images.githubusercontent.com/3169354/219344856-8cdece92-c1d9-42d1-a86d-530c6f3309b4.png)

2023-02-16 14:16 UTC, grotlue requested changes
The text looks good now!

However, while checking it again I realised that something is off when changing the entries per page size.

With 52 test entries
- ✅ it shows all on one page when the page is set to 100
- ❌ it shows all on one page when the page size is set to 50 (expected: 2 pages)
- ❌ it shows all on two pages when the page size is set to 25 (expected 3 pages)

2023-02-21 14:40 UTC, ousmaneo commented
Hi @grotlue, as we discussed, I removed the page size selector as in this case, it does not make sense since we are listing collectors state and not just sidecars.

2023-02-21 14:57 UTC, grotlue approved these changes
Let's merge this! (once the build is green)

2023-02-22 08:05 UTC, merged

2023-06-12 15:01 UTC, williamtrelawny commented
Hi @ousmaneo can you confirm for me which version (and backports if any) this was released to? I don't see anything about this in the [Release Announcements](https://graylogdocumentation.atlassian.net/wiki/spaces/GLE/pages/2593095922/Release+Announcements)

2023-06-13 06:25 UTC, ousmaneo commented
Hi William this was merged and released with [5.1.0-beta.1](https://github.com/Graylog2/graylog2-server/releases/tag/5.1.0-beta.1). And  does not have any backports.