Issue 14433
Graylog2/graylog2-server pull request #14459
Opened 2023-01-17 13:39 UTC by thll

WIP

Support encrypted values in input configuration.
Make use of it in the HTTP JSON Path Input.

fixes #14433 

TODO:
- [ ] forwarder support
- [ ] content pack support
- [ ] UI

2023-02-06 17:00 UTC, AntonEbel requested changes

2023-02-08 10:06 UTC, AntonEbel approved these changes
Backend LGTM.

2023-02-13 17:24 UTC, grotlue commented
I added the support of encrypted values in the Input Configuration form and view.

https://user-images.githubusercontent.com/3169354/218528210-89930b5f-5ea7-442c-b73e-6196d6f7b50d.mp4

2023-02-23 11:52 UTC, ousmaneo requested changes
Looks good! I added some comments

2023-02-23 15:52 UTC, grotlue commented on graylog2-web-interface/src/components/configurationforms/index.jsx
> +export { default as ConfigurationForm } from './ConfigurationForm'; // eslint-disable-line import/no-cycle
That is true, but I think it is complaining in the cloud-inputs branch, which is based on this one. I thought I'd change it here already.

2023-02-24 14:08 UTC, ousmaneo approved these changes
Tested it again and I think we good to go 🎉

2023-02-24 14:11 UTC, merged