Allowing Entities to have no Title in Excerpts
Graylog2/graylog2-server pull request #14539
Opened 2023-01-27 09:57 UTC by janheise

## Description

## Motivation and Context

Stream Filters are the first type of entities that are allowed to have no title. So the resolver has to be fixed to allow this.

/nocl

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-01-27 16:43 UTC, linuspahl reviewed
Fixes the described problems for me.

2023-02-02 11:15 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
> +                        v -> v.title() != null ? Optional.of(v.title()) : Optional.empty()));
```suggestion
                        v -> Optional.ofNullable(v.title()));
```
this should work too

2023-02-02 11:18 UTC, mpfz0r requested changes
one small nitpick

2023-02-02 11:22 UTC, mpfz0r approved these changes

2023-02-02 12:20 UTC, merged