Add runtime failure tracking to polling inputs
Graylog2/graylog2-server pull request #14726
Opened 2023-02-20 15:14 UTC by mpfz0r

Inputs that are polling their data, can experience intermittent failures. So far, those were only logged as errors in the server.log. There was no way to find these failures in the UI.

Introduce a new input IOState "Failing" which indicates those errors.

Add a new InputFailureRecorder to MessageInput.launch() which then can be passed to the Transports of various Inputs, and replace the LOG.errors certain calls.
The InputFailureRecorder can also be used to clear the failing input state, once the error is resolved.

Inputs that want to make use of the new InputFailureRecorder should inherit their Transports from ThrottleableTransport2, which has the new launch/doLaunch signature.

In addition, the SystemNotification for failing Inputs could not handle multiple Inputs at the time. To accomodate for this, we introduce an optional "key" for SystemNotifications. This allows us to differentiate between multiple Inputs.

2023-03-08 09:26 UTC, thll requested changes

2023-03-08 10:44 UTC, thll commented
@mpfz0r, is there a companion PR for the Forwarder? Unless we make the changes to `NotificationService.java` backwards compatible, we are going to need one:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project graylog-forwarder: Compilation failure: Compilation failure:
[ERROR] /Volumes/CaseSensitive/git/forwarder/forwarder/src/main/java/org/graylog/forwarder/config/NoopNotificationService.java:[16,7] error: NoopNotificationService is not abstract and does not override abstract method destroyAllByTypeAndKey(Type,String) in NotificationService
[ERROR] /Volumes/CaseSensitive/git/forwarder/forwarder/src/main/java/org/graylog/forwarder/config/NoopNotificationService.java:[48,4] error: method does not override or implement a method from a supertype
```

2023-03-08 11:02 UTC, thll commented
I've also noticed that in the Forwarder, we are not considering a `FAILING` input to be running, so that requires a change as well:

```
2023-03-08T12:00:47.625+0100 INFO  [scheduled-daemon-9] control.configuration.ConfigurationProcessor - Server requested input [[JSON path/64086953975fbb4ef727ffaf]] to be started. Current state of input: [FAILING].
```

2023-03-08 14:30 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/ThrottleableTransport2.java
> +    protected void doLaunch(MessageInput input) throws MisfireException {
ah. good idea.

2023-03-08 14:51 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/plugin/InputFailureRecorder.java
> +        LoggerFactory.getLogger(clazz).warn(error, e);
yeah, I'm gonna go for option 2 :+1:

2023-03-08 15:48 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/plugin/InputFailureRecorder.java
> +public class InputFailureRecorder {
yeah. fixing

2023-03-08 17:16 UTC, mpfz0r commented
> I've also noticed that in the Forwarder, we are not considering a `FAILING` input to be running, so that requires a change as well:

Thanks! 
This should do it: 
https://github.com/Graylog2/forwarder/pull/96
https://github.com/Graylog2/graylog-plugin-enterprise/pull/4822

2023-03-09 09:15 UTC, thll approved these changes

2023-03-09 09:16 UTC, thll commented
Great feature. Thank you for going through with it :pray:

2023-03-09 11:03 UTC, merged