Index Set Page Performance Improvements
Graylog2/graylog2-server pull request #15155
Opened 2023-04-05 12:16 UTC by grotlue

Part of: https://github.com/Graylog2/graylog2-server/issues/12498

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-04-25 15:52 UTC, mpfz0r approved these changes
LGTM :+1:  
We won't be merging this into 5.1, right?

2023-04-26 05:52 UTC, kodjo-anipah commented
> LGTM 👍 We won't be merging this into 5.1, right?

Yeah lets wait after 5.1 is done

2023-04-26 12:22 UTC, gally47 requested changes
Frontend looking good, just one suggestion.

2023-04-26 12:22 UTC, gally47 commented on graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx
> +                      label="Search"
I think we should keep the search field UI consistent in all the views by removing the `label` and putting the field on the `left side`. For the stats info we can either put it below the search field or in the right side.

2023-04-27 08:28 UTC, gally47 approved these changes
LGTM!

2023-05-04 08:28 UTC, merged