feat: system notification on sidecar inactive
Graylog2/graylog2-server pull request #15222
Opened 2023-04-14 07:51 UTC by moesterheld

create a message in the system notification stream when a sidecar becomes inactive

## Description
when a sidecar gets the status `UNKNOWN`, a message is generated in the system notification stream.

## Motivation and Context
resolves #6697 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-04-18 13:06 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/Configuration.java
> +    private Set<String> systemEventExcludedTypes = Sets.newHashSet(Notification.Type.SIDECAR_STATUS_UNKNOWN.name());
we usually document these settings and their defaults in  `misc/graylog.conf`

2023-04-18 13:46 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/SidecarService.java
> +                            Notification notification = notificationService.buildNow();
this could be extracted into a separate method to increase readability

2023-04-18 13:49 UTC, mpfz0r requested changes
Left a few comments. 
I wonder if we can find a better name and wording for "status unknown"
Sounds very abstract.  Maybe something like "Lost contact to sidecar" or the likes? :thinking:

2023-04-24 08:40 UTC, moesterheld commented
> Left a few comments. I wonder if we can find a better name and wording for "status unknown" Sounds very abstract. Maybe something like "Lost contact to sidecar" or the likes? 🤔

"Unknown" is also the status shown for the sidecars in the UI, so I think it is the one the user can relate to the best. 

There would also be a Status FAILING (currently unused), which also isn't really correct I would say. The method setting the state to UNKNOWN is called markExpired.

2023-04-26 08:15 UTC, mpfz0r commented on misc/graylog.conf
> +# Default: SIDECAR_STATUS_UNKNOWN which will create a new type whenever the status of a sidecar becomes "Unknown"
```suggestion
# Default: SIDECAR_STATUS_UNKNOWN which will create a new event whenever the status of a sidecar becomes "Unknown"
```

2023-04-26 08:20 UTC, mpfz0r commented on misc/graylog.conf
> +# Default: SIDECAR_STATUS_UNKNOWN which will create a new event whenever the status of a sidecar becomes "Unknown"
```suggestion
# Default: SIDECAR_STATUS_UNKNOWN which would create a new event whenever the status of a sidecar becomes "Unknown"
```

Sorry, you clicked faster then I was able to correct my suggestion  :-D

2023-04-26 08:59 UTC, mpfz0r approved these changes
LGTM. 
Since we are only merging this after 5.1 we might get the chance to improve the system events system to make this a bit less hacky

2023-08-17 11:26 UTC, mpfz0r commented
build currently fails with `[2023-08-16T08:58:29.022Z] [ERROR] /home/jenkins/workspace/apshots_graylog2-server_PR-15222/.repos/graylog-plugin-enterprise/enterprise/src/main/java/org/graylog/plugins/cloud/command/NullNotificationServiceImpl.java:[23,7] error: NullNotificationServiceImpl is not abstract and does not override abstract method createSystemEvent(Notification) in NotificationService`

2023-09-15 08:33 UTC, mpfz0r commented
@moesterheld sorry this took so long :sweat_smile:  feel free to merge when it's green

2023-09-18 10:24 UTC, merged