add `sidecars:read` to Sidecar System role
Graylog2/graylog2-server pull request #15380
Opened 2023-04-28 08:21 UTC by moesterheld

## Description
Add `sidecars:read` permission to Sidecar System user
/nocl

## Motivation and Context
closes #12044 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-05-11 13:18 UTC, AntonEbel requested changes

2023-06-29 09:17 UTC, AntonEbel requested changes
Just some minor things and one thing for the `Sidecar Reader` role. Currently, this user can click on the edit and update buttons, which results in an error page. I think it would improve the UX if someone from the frontend team would hide these buttons for the reader role. I don't know if we should make these changes in this PR or create an issue for that.

2023-06-29 09:17 UTC, AntonEbel commented on changelog/unreleased/pr-15380.toml
> +message = "Add Sidecar Manager role to read and manage sidecars."
Perhaps we should also mention here the role of the `Sidecar Reader`.

2023-06-29 09:17 UTC, AntonEbel commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20230502164900_AddSidecarManagerRole.java
> +public class V20230502164900_AddSidecarManagerRole extends Migration {
Maybe `V20230502164900_AddSidecarManagerAndReaderRole`?

2023-06-30 12:55 UTC, AntonEbel approved these changes
LGTM

2023-07-07 09:14 UTC, mpfz0r approved these changes
LGTM as well :+1:

2023-07-25 08:53 UTC, merged

2023-09-05 12:17 UTC, ryan-carroll-graylog commented
@kroepke @moesterheld @AntonEbel can this be backported to 5.0?

There's a HubSpot issue open for another customer with this same issue (HS-1821909158) who's on Graylog 5.0.10.