add max leeway configuration and validation
Graylog2/graylog2-server pull request #15556
Opened 2023-05-22 16:32 UTC by kodjo-anipah

part of Graylog2/graylog-plugin-cloud#1149
## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-05-23 14:41 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
> +    private Period timeSizeOptimizingRotationFixedLeeway = Period.days(1);
for on-prem we don't want this to be on by default.
can we set the default to null? and only validate it if it's set?

2023-05-23 14:45 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java
> +            if (leeway.toStandardSeconds().isLessThan(elasticsearchConfiguration.getTimeSizeOptimizingRotationFixedLeeway().toStandardSeconds())) {
i would keep this validation and add a new separate fixed leeway validation (which is off by default (see above comment))

2023-05-23 14:51 UTC, mpfz0r requested changes
two comments, rest looks good on a first glance

2023-05-23 18:46 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
> +    public Period getTimeSizeOptimizingRotationFixedLeeway() {
```suggestion
    @Nullable
    public Period getTimeSizeOptimizingRotationFixedLeeway() {
```

2023-05-24 11:03 UTC, mpfz0r commented on graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java
> +
```suggestion
```

we don't need this anymore

2023-05-24 11:05 UTC, mpfz0r commented on graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java
> +        when(elasticsearchConfiguration.getTimeSizeOptimizingRotationFixedLeeway()).thenReturn(Period.days(1));
```suggestion
```
same here

2023-05-24 14:15 UTC, mpfz0r approved these changes
LGTM :+1:

2023-05-24 15:58 UTC, kodjo-anipah reviewed
<img width="733" alt="image" src="https://github.com/Graylog2/graylog2-server/assets/98284293/904e1693-8180-4988-87f7-832021f3b7b7">
looks good now

2023-05-24 18:40 UTC, merged