Ready-to-use sidecar configurations
Graylog2/graylog2-server pull request #15571
Opened 2023-05-23 10:31 UTC by AntonEbel

## Description

- add graylog_host variable and use it in templates
- add default configurations for windows and linux with `default` tag
- add Auditbeat collector for Linux

part of #15570

2023-05-26 12:20 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
> +        ).ifPresent(collector -> ensureDefaultConfiguration("default-windows", collector));
```suggestion
        ).ifPresent(collector -> ensureDefaultConfiguration("winlogbeat-default", collector));
```
I'd rather name that after the collector. the OS is implicit. actually the collector is too, but I think it looks better this way

2023-05-26 12:20 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
> +        ).ifPresent(collector -> ensureDefaultConfiguration("default-linux", collector));
```suggestion
        ).ifPresent(collector -> ensureDefaultConfiguration("auditlogbeat-default", collector));
```
I'd rather name that after the collector. the OS is implicit. actually the collector is too, but I think it looks better this way

2023-05-26 12:21 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
> +                )
no default config for linux filebeat?

2023-06-07 12:26 UTC, mpfz0r commented
apart from my comments this LGTM. I guess you wanted to extend the configs with the feedback from sec-dev?

2023-06-19 14:41 UTC, AntonEbel commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
> +                LOG.error("Can't save sidecar default configuration '{}', please restart Graylog to fix this.", name, e);
removed the "please restart Graylog to fix this." part.

2023-08-08 14:46 UTC, AntonEbel commented
We have discussed with @kroepke  that we will continue without a new Winlogbeat configuration.

2023-08-11 07:41 UTC, mpfz0r approved these changes

2023-08-11 07:43 UTC, mpfz0r commented on graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
> +                LOG.error("Couldn't find sidecar configuration variable '{}' fixing it.", name);
```suggestion
                LOG.info("Couldn't find sidecar configuration variable '{}' fixing it.", name);
```
This is not an error

2023-08-11 07:44 UTC, mpfz0r requested changes
one nitpick rest looks good

2023-08-18 09:19 UTC, mpfz0r approved these changes

2023-08-18 13:19 UTC, merged