small fixes, additions to rulebuilder
Graylog2/graylog2-server pull request #15785
Opened 2023-06-20 14:36 UTC by moesterheld

## Description
- sort function names
- add implicit to_string fragments
- fix string parameter and primary parameter handling in fragments

## Screenshots (if appropriate):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-06-21 13:46 UTC, kodjo-anipah commented on graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230613154400_AddImplicitToStringFragments.java
> +                          value: to_string(),
to_string(${value}),

2023-06-21 15:09 UTC, moesterheld commented on graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230613154400_AddImplicitToStringFragments.java
> +                          value: to_string(),
good catch

2023-06-22 05:47 UTC, kodjo-anipah requested changes
There seems to be an problem with output variables couldn't test the date fragment. 
Also we should deactivate Rulebuilder for FormatDate.java

2023-06-22 09:01 UTC, moesterheld commented
> There seems to be an problem with output variables couldn't test the date fragment.

Problem is fixed

> Also we should deactivate Rulebuilder for FormatDate.java

I would have liked to have this available to use `get_date` to parse the date and then use `format_date` to create a string with another format. But I think we have to talk about how to handle dates in the UI in the next cycle as the date won't be available for setting in the form currently. I will deactivate it for now.

2023-06-22 12:50 UTC, kodjo-anipah approved these changes
tested all functions and conditions , LGTM

2023-06-23 09:08 UTC, merged