Mark users from deactivated auth backend
Graylog2/graylog2-server pull request #16134
Opened 2023-08-08 12:39 UTC by moesterheld

## Description
If an authentication backend is deactivated, users will still retain their enabled/disabled flags.
However, in the overview page the icon is always greyed out with a tooltip describing the issue.
In the user details page, the hint is displayed below the status.

## Motivation and Context
fixes #13823 

## Screenshots (if appropriate):
Users Overview: 
![image](https://github.com/Graylog2/graylog2-server/assets/33032967/2bd9db30-fe4a-475c-82a5-d29634a2d313)

User Detail:
![image](https://github.com/Graylog2/graylog2-server/assets/33032967/b1c327f7-62d7-4f36-adf7-ddf868211350)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-08-11 07:56 UTC, patrickmann requested changes
Works as expected. Just some housekeeping comments.

2023-08-11 08:45 UTC, moesterheld commented on graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java
> +            return this;
You are right. The settings were at 'whole file' after disabling the 'Save Actions' plugin. 
Should I try to rollback the changes in the unchanged lines?

2023-08-15 07:15 UTC, patrickmann approved these changes
Approving, as my suggestions are unrelated to the code change itself.
I still think we should try and resolve TODOs whenever modifying a file, but it's not a blocker.

2023-08-16 14:23 UTC, moesterheld commented on graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
>  import org.apache.shiro.session.Session;
Unfortunately, the api param is called idOrToken.
Since it should be renamed at the same time, we have a breaking change which should be done in 6.0

2023-08-18 06:47 UTC, merged