Merging `integrations` plugin.
Graylog2/graylog2-server pull request #16274
Opened 2023-08-25 08:38 UTC by dennisoelkers

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-08-28 06:54 UTC, bernd reviewed
@dennisoelkers Let's put the Java code into the `graylog2-server/src/main/java/org/graylog/plugins` directory like we did for the recent threatintel plugin merge and where the other merged plugins are.

```
$ ls -l graylog2-server/src/main/java/org/graylog/plugins/
total 32
drwxr-xr-x  2 bernd bernd 4096 Jun 21 15:51 beats
drwxr-xr-x  6 bernd bernd 4096 Jun 21 15:51 cef
drwxr-xr-x  4 bernd bernd 4096 Jun 21 15:51 map
drwxr-xr-x  9 bernd bernd 4096 Jun  9  2021 netflow
drwxr-xr-x 13 bernd bernd 4096 Jun 21 15:51 pipelineprocessor
drwxr-xr-x 13 bernd bernd 4096 Jul 31 08:26 sidecar
drwxr-xr-x  7 bernd bernd 4096 Jun 21 15:51 threatintel
drwxr-xr-x  8 bernd bernd 4096 Jun 28 12:19 views
```

2023-08-29 07:17 UTC, dennisoelkers commented
@bernd: I thought about that too, but unfortunately parts of our paths are also bound to the package name of the plugin, so I refrained from moving it in this PR to avoid introducing regressions. I would still like to do it, but in a follow-up PR so I can focus on it.

2023-08-29 09:35 UTC, bernd commented
> @bernd: I thought about that too, but unfortunately parts of our [REST api paths](https://github.com/Graylog2/graylog2-server/pull/16274/files#diff-def568a64c08113b87488f427366afc1e6b0db85054c98a7ac0f77c604efc907R30-R43) are also bound to the package name of the plugin, so I refrained from moving it in this PR to avoid introducing regressions. I would still like to do it, but in a follow-up PR so I can focus on it.

@dennisoelkers Ah, right. I missed that. Thanks!

2023-08-29 13:33 UTC, bernd requested changes
@dennisoelkers Let's add a `package-info.java` file with the note about the package name like we did for the AWS plugin: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/aws/package-info.java

2023-08-29 13:33 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/integrations/Integrations.java
> +public class Integrations {
This file seems to be unused.

2023-08-29 14:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Graylog2/graylog2-server?pullRequest=16274) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Graylog2/graylog2-server?pullRequest=16274) before we can accept your contribution.<br/>**17** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: waab76<br/>:white_check_mark: mpfz0r<br/>:white_check_mark: kyleknighted<br/>:white_check_mark: dennisoelkers<br/>:white_check_mark: kingzacko1<br/>:white_check_mark: roberto-graylog<br/>:white_check_mark: thll<br/>:white_check_mark: danotorrey<br/>:white_check_mark: casperbiering<br/>:white_check_mark: linuspahl<br/>:white_check_mark: todvora<br/>:white_check_mark: zeeklop<br/>:white_check_mark: ryan-carroll-graylog<br/>:white_check_mark: AntonEbel<br/>:white_check_mark: moesterheld<br/>:white_check_mark: luk-kaminski<br/>:white_check_mark: jaak-pruulmann-sympower<br/>:x: claudia<br/><hr/>**claudia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Graylog2/graylog2-server?pullRequest=16274) it.</sub>

2023-08-29 14:52 UTC, dennisoelkers commented on graylog2-server/src/main/java/org/graylog/integrations/Integrations.java
> +public class Integrations {
:white_check_mark:

2023-08-29 14:56 UTC, dennisoelkers commented
@bernd: Thanks for the hint! Added the `package-info.java`.

2023-08-29 20:40 UTC, danotorrey approved these changes
@dennisoelkers This LGTM and tests successfully. All the code is migrated, and the package names line up. Well done!

I successfully tested creating an AWS Kinesis/Cloudwatch input, the Slack/Teams notification, and the DNS Adapter pre-upgrade (without this PR checked-out). All work successfully after upgrade, and also can be edited/created after successfully too.

2023-08-29 21:35 UTC, kingzacko1 approved these changes

2023-08-30 06:53 UTC, bernd approved these changes
My comments got addressed. I only looked at some code infrastructure changes and did not test the plugin.

Thanks, @dennisoelkers! :pray:

2023-08-30 07:37 UTC, merged