Telemetry event
Graylog2/graylog2-server pull request #16317
Opened 2023-08-30 05:44 UTC by ousmaneo

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-09-28 13:50 UTC, grotlue requested changes
In general it looks good. While testing I found some issues. I think a few just be fixed (the bug for example) but some would be nice to have and we can also discuss/create follow-up issues for that

## Test results
I tested some general tracking test cases. Additionally, I picked sections based on the code and did regression testing on those due to time constraints.
Let me know if I should test something specific or anything else.

### General
✅ Pageview is tracked as usual
✅ Group Identify is tracked as usual
✅ Tracking is not fired when disabled
✅ Opt out event is tracked
✅ Opt in event is tracked

### Streams
❌ Click on start/stop stream in the status column is not tracked
❌ `Stream Item Clone Modal Opened` is tracked twice
❌ `Stream Item Deleted` is tracked when clicking on Delete even when clicking cancel and not actually deleting the stream afterwards

### Search
❌ multiple actions are still tracked with generic events (`input_button_toggle`, `click`, `form_submit`)

### Rules & Pipelines
No issues found
### Events
I wasn't able to test tracking when events and notifications are created due to the bug

❌ When attempting to create a simple event definition with a `value=true` search filter I encountered the following error: 
![Screenshot 2023-09-28 at 12 46 16](https://github.com/Graylog2/graylog2-server/assets/3169354/ade6f13e-d63d-4cad-8ccb-63dbe6390e34)

❌ No tracking for create event notification button click event (but we have it for (`EventDefinition Create Button Clicked`)

### Content Stream
❌ Opening a news article and a release are both tracked with `Content Stream Article Clicked` other clicks are categorized into Releases and News. It would be good to track a release article click separately. 

### Dashboards
No issues found

2023-09-28 14:21 UTC, ousmaneo commented
Hi Thank you for reviewing,

> ❌ multiple actions are still tracked with generic events (input_button_toggle, click, form_submit)

Do you have some example for `input_button_toggle` and `click` I only found 2 `form_submit` event?

2023-09-28 15:02 UTC, grotlue commented
> Hi @grotlue Thank you for reviewing,
> 
> > ❌ multiple actions are still tracked with generic events (input_button_toggle, click, form_submit)
> 
> Do you have some example for `input_button_toggle` and `click` I only found 2 `form_submit` event?

Oh I should have written them down. One example is search filter create for `click`.

2023-09-28 15:35 UTC, ousmaneo commented
@grotlue I think you were missing the enterprise branch. It was linked from the enterprise branch but not on the dependency list on this one.

2023-09-28 15:44 UTC, ousmaneo commented on graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
> +instant_archiving=on
I reverted it after noticing

2023-09-28 15:46 UTC, ousmaneo commented on graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx
> +        posthog.identify(user, { ...userDetails, ...getGlobalProps(telemetryData) });
These contain different data so I think it is safe.

2023-09-28 15:54 UTC, ousmaneo commented on graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.tsx
> +        app_section: 'new-event-definition',
For the scope of this PR, we decided to change only the event names and some `event_details`. We might update how we set the app_section in the follow-up work.

2023-09-28 16:09 UTC, grotlue commented
> @grotlue I think you were missing the enterprise branch. It was linked from the enterprise branch but not on the dependency list on this one.

Ah yes I did not know about that one.

2023-09-28 16:17 UTC, grotlue commented on graylog2-web-interface/src/components/streams/StreamsOverview/cells/StatusCell.tsx
> +      app_action_value: ' stream-item-status',
```suggestion
      app_action_value: 'stream-item-status',
```

2023-09-28 16:25 UTC, grotlue commented
Thanks for the fixes, I already tested the following issues (checked == fixed) and they look good now!
However, one new issue came up:

❌ Stream deletion is not tracked at all anymore (also when actually deleting the stream)


### Streams

- [x] ❌ Click on start/stop stream in the status column is not tracked
- [x] ❌ Stream Item Clone Modal Opened is tracked twice
- [x] ❌ Stream Item Deleted is tracked when clicking on Delete even when clicking cancel and not actually deleting the stream afterwards


### Search

- [x] ❌ multiple actions are still tracked with generic events (input_button_toggle, click, form_submit)


### Content Stream

- [x] ❌ Opening a news article and a release are both tracked with Content Stream Article Clicked other clicks are categorized into Releases and News. It would be good to track a release article click separately.

2023-09-29 08:39 UTC, grotlue approved these changes
Had another look, thanks for fixing all those issues! 👍 

## The following are fixed:
> ❌ When attempting to create a simple event definition with a value=true search filter I encountered the following error:
> ❌ Stream deletion is not tracked at all anymore (also when actually deleting the stream)


## Open issues
The tracking for event creation also looks good. The only thing left here is the tracking for event notification creation. 
I think we can still merge all the other things and fix it in another PR, but we should create an issue for that.

2023-09-29 10:40 UTC, merged

2023-10-02 08:27 UTC, linuspahl commented
@ousmaneo @grotlue I saw there are some cases where we are now using a `button` instead of an `anchor` for links. For example for the "Create event definition" link. We mainly removed the `LinkContainer`. Couldn't we just add `onClick` for the `Button` or `LinkContainer` component?

My concern is that this change has some disadvantages, like worse accessibility. For example I noticed you can no longer do "open in new tab" by right clicking on the link and selecting the option or by pressing Command or Ctrl and clicking on the link.

2023-10-11 07:27 UTC, ousmaneo commented
> @ousmaneo @grotlue I saw there are some cases where we are now using a `button` instead of an `anchor` for links. For example for the "Create event definition" link. We mainly removed the `LinkContainer`. Couldn't we just add `onClick` for the `Button` or `LinkContainer` component?
> 
> My concern is that this change has some disadvantages, like worse accessibility. For example I noticed you can no longer do "open in new tab" by right clicking on the link and selecting the option or by pressing Command or Ctrl and clicking on the link.


Hi @linuspahl, Thank you for your comment. I think you are right instead of changing the component of the` Create event definition` to a button, we could add a onClick to the child button to trigger the telemetry call. The LinkContainer is already designed to call the onClick on the child button. I will create an Issue for it.