Datanode: Using retryer for connectivity check, hiding exceptions
Graylog2/graylog2-server pull request #16771
Opened 2023-09-29 12:03 UTC by janheise

## Description

TODO: multithreading

/nocl

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-09-29 14:23 UTC, dennisoelkers requested changes
This is not ideal from my point of view:

  - Instead of blocking the periodical, this is now consuming threads from the `daemonScheduler`. With a frequency of 2 seconds, this could lead to an overconsumption of threads when one or more nodes are not reachable
  - The connectivity check per node is unnecessarily delayed by 1 second

2023-10-02 12:23 UTC, todvora commented
This seems like a task for a state machine. We are doing something similar internally in the datanode - we know that it started, configure how many failures are allowed and what to do when the counter is depleted or the call succeeds. Maybe we could do to same here.

2023-10-06 08:16 UTC, janheise commented
I changed the thread pool to a cached thread pool which should be exactly what we want regarding resource usage here (unless you add hundreds of datanodes during preflight). see https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/Executors.html#newCachedThreadPool()

2023-10-09 11:13 UTC, dennisoelkers approved these changes

2023-10-10 12:04 UTC, dennisoelkers approved these changes

2023-10-10 12:04 UTC, merged