Fix opensearch configuration sync permissions
Graylog2/graylog2-server pull request #17059
Opened 2023-10-24 11:29 UTC by todvora

/nocl

This PR adapts permissions of opensearch configuration files that we sync(=copy and generate) during each datanode startup.

## Motivation and Context
We should fix not just key material permissions as requested in https://github.com/Graylog2/graylog2-server/issues/17009 but all config files used by the embedded OS.

## How Has This Been Tested?
Added unit test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

2023-10-24 14:19 UTC, moesterheld approved these changes
works as expected. lgtm

2023-10-26 07:36 UTC, janheise requested changes
LGTM, but needs a changelog file

2023-10-27 07:35 UTC, todvora commented
@janheise as I understood it, we don't want changelog entries for products that are not released yet.

2023-10-27 07:40 UTC, janheise commented
@todvora but 5.2 will be released without this, so it goes into the first bugfix release - and needs a changelog imho

2023-10-27 12:42 UTC, janheise approved these changes

2023-11-02 07:36 UTC, merged