Datanode List Page UI
Graylog2/graylog2-server pull request #17161
Opened 2023-11-02 16:08 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/17159

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-12-15 14:42 UTC, grotlue requested changes
Below are the results of testing this PR.
I still need to test the sorting functionality of the columns "Name" and "Is leader" and the searching but I still need to figure out how to manipulate these fields.
I found some issues with this list, I will review the code afterwards.

## Test results
✅Data Node List shows all data nodes with "Name", "Transport address", "Status", "Is leader", "Certificate valid until" and "Actions"
✅When clicking on "More" in the "Actions" column it shows the following actions
	- Renew certificate
	- Start
	- Stop
	- Rejoin
	- Remove
❌ The action "Stop" should only be shown for running data nodes
❌ The action "Start" should only be shown for stopped data nodes
✅When clicking on "Stop" it shows a notification
✅When clicking on "Stop" the status changes from "Available" to "Unavailable"
✅When clicking on "Start" it shows a notification
✅When clicking on "Start" the status changes from "Unavailable" to "Starting" to "Available"
❌ Entries can be sorted by "Status"
❌ Entries can be sorted by "	Certificate valid until"
❌ The search syntax help shows information about searchable fields in this list -> Shows fields that are not in the list, like `id`, `description`
✅Clicking on the name leads to the detail view
✅Columns can be hidden and shown using the "Columns" dropdown on the right
✅A "Data Nodes documentation" link on the top right redirects to the official Graylog Documentation for Data Nodes
✅When clicking "Renew certificate" it shows a success notification
When clicking "Renew certificate" the certificate is renewed
⚠️ The confirmation modal for "Rejoin" talks about resetting the Data Node. The naming is not consistent and thus confusing. I'd suggest to change "reset" to "rejoin" in the modal.
✅When clicking "Remove" a confirmation modal is shown
✅When confirming the removal a success notification is shown
✅When confirming the removal the status changes to "Removing" and later to "Removed"
✅When clicking "Rejoin" a confirmation modal is shown
✅When confirming rejoining a success notification is shown
✅When confirming rejoining the status changes to "Unconfigured"
❌ When confirming rejoining the status does not change further and stays "Unconfigured", however in preflight mode nothing else can be configured for this Data Node
❌ When removing a rejoined Data Node which is stuck on "Unconfigured" it shows a success message, but the status does not change 
✅Entries can be sorted by "Name"
✅Entries can be sorted by "Is leader"
❌ Entries can be searched by "Name"

2023-12-18 15:18 UTC, grotlue requested changes
Code looks good in general. However, I think we should go through all the copy and make sure we use one spelling of `Data Node`.

2023-12-18 15:18 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Removing Datanode failed with status: ${errorThrown}`, 'Could not Remove the Datanode.');
```suggestion
    UserNotification.error(`Removing Datanode failed with status: ${errorThrown}`, 'Could not remove the Datanode.');
```

2023-12-18 15:18 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Stopping Datanode failed with status: ${errorThrown}`, 'Could not Stop the Datanode.');
```suggestion
    UserNotification.error(`Stopping Datanode failed with status: ${errorThrown}`, 'Could not stop the Datanode.');
```

2023-12-18 15:18 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Rejoining Datanode failed with status: ${errorThrown}`, 'Could not Rejoin the Datanode.');
```suggestion
    UserNotification.error(`Rejoining Datanode failed with status: ${errorThrown}`, 'Could not rejoin the Datanode.');
```

2023-12-18 15:18 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +        UserNotification.error(`Loading datanodes failed with status: ${errorThrown}`,
Same here, another way to spell `datanodes`.

2023-12-18 15:18 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesClusterPage.tsx
> +        Graylog data nodes offer a better integration with Graylog and simplify future updates. They allow you to index and search through all the messages in your Graylog message database.
Same with the spelling `data nodes`.

2023-12-18 15:18 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
> +        Graylog data nodes offer a better integration with Graylog and simplify future updates. They allow you to index and search through all the messages in your Graylog message database.
Same here. (spelling)

2023-12-19 09:54 UTC, ousmaneo commented
Thank you for your test and review. I fixed all the frontend-related comments. For these below, we will need to adjust the backend; for example, for the search-related issue, the frontend is sending the right request, same for the sorting.

> ❌ Entries can be sorted by "Status"
> ❌ Entries can be sorted by " Certificate valid until"
> ❌ When confirming rejoining the status does not change further and stays "Unconfigured", however in preflight mode nothing else can be configured for this Data Node
> ❌ When removing a rejoined Data Node which is stuck on "Unconfigured" it shows a success message, but the status does not change
> ❌ Entries can be searched by "Name"

2023-12-19 15:51 UTC, moesterheld commented
> ❌ Entries can be sorted by "Status"
> ❌ Entries can be sorted by " Certificate valid until"

I have created a issue for these, as making that available is not trivial. Maybe the sorting button could be hidden in these columns in the UI in the meantime?

2023-12-19 17:46 UTC, grotlue requested changes
Thanks a lot for the fixes!

I still found inconsistencies in the copy, so I went through all the files and commented suggestions so it's easier to track an update. I suggested to go with `Data Node`/`Data Nodes`, using it as a term/own name.


> > ❌ Entries can be sorted by "Status"
> > ❌ Entries can be sorted by " Certificate valid until"
> 
> I have created a issue for these, as making that available is not trivial. Maybe the sorting button could be hidden in these columns in the UI in the meantime?

I think this is a good idea, so we don't merge something broken.

I retested the other cases and they look fine now! However, I added to more cases which I think should be adjusted.

### Test results
✅ Entries can be searched by "Name"
✅ When confirming rejoining the status does not change further and stays "Unconfigured", however in preflight mode nothing else can be configured for this Data Node
✅ ~When removing a rejoined Data Node which is stuck on "Unconfigured" it shows a success message, but the status does not change~
✅ The search syntax help shows information about searchable fields in this list -> Shows fields that are not in the list, like id, description
✅ The action "Stop" should only be shown for running data nodes
✅ The action "Start" should only be shown for stopped data nodes
✅ ~The confirmation modal for "Rejoin" talks about resetting the Data Node. The naming is not consistent and thus confusing. I'd suggest to change "reset" to "rejoin" in the modal.~

❌ The action "Rejoin" should only be shown for removed data nodes
❌ The action "Remove" should only be for data nodes that are not already removed

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogTitle: 'Rejoin Datanode',
```suggestion
    dialogTitle: 'Rejoin Data Node',
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogBody: (datanode: string) => `Are you sure you want to rejoin datanode "${datanode}"?`,
```suggestion
    dialogBody: (datanode: string) => `Are you sure you want to rejoin Data Node "${datanode}"?`,
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogTitle: 'Remove datanode',
```suggestion
    dialogTitle: 'Remove Data Node',
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogBody: (datanode: string) => `Are you sure you want to remove datanode "${datanode}"?`,
```suggestion
    dialogBody: (datanode: string) => `Are you sure you want to remove Data Node "${datanode}"?`,
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogTitle: 'Stop datanode',
```suggestion
    dialogTitle: 'Stop Data Node',
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogBody: (datanode: string) => `Are you sure you want to stop datanode "${datanode}"?`,
```suggestion
    dialogBody: (datanode: string) => `Are you sure you want to stop Data Node "${datanode}"?`,
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeList.tsx
> +          <NoSearchResult>No Data Nodes have been found</NoSearchResult>
Here the spelling would already fit 👍

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.success(`Datanode "${datanodeId}" removed successfully`);
```suggestion
    UserNotification.success(`Data Node "${datanodeId}" removed successfully`);
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Removing Data node failed with status: ${errorThrown}`, 'Could not remove the Datanode.');
```suggestion
    UserNotification.error(`Removing Data Node failed with status: ${errorThrown}`, 'Could not remove the Data Node.');
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.success(`Data node "${datanodeId}" started successfully`);
```suggestion
    UserNotification.success(`Data Node "${datanodeId}" started successfully`);
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Starting Data node failed with status: ${errorThrown}`, 'Could not start the Datanode.');
```suggestion
    UserNotification.error(`Starting Data Node failed with status: ${errorThrown}`, 'Could not start the Data Node.');
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.success(`Data node "${datanodeId}" stopped successfully`);
```suggestion
    UserNotification.success(`Data Node "${datanodeId}" stopped successfully`);
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Stopping Data node failed with status: ${errorThrown}`, 'Could not stop the Datanode.');
```suggestion
    UserNotification.error(`Stopping Data Node failed with status: ${errorThrown}`, 'Could not stop the Data Node.');
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.success(`Data node "${datanodeId}" rejoined successfully`);
```suggestion
    UserNotification.success(`Data Node "${datanodeId}" rejoined successfully`);
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +    UserNotification.error(`Rejoining Data node failed with status: ${errorThrown}`, 'Could not rejoin the Datanode.');
```suggestion
    UserNotification.error(`Rejoining Data Node failed with status: ${errorThrown}`, 'Could not rejoin the Data Node.');
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +        UserNotification.error(`Loading data nodes failed with status: ${errorThrown}`,
```suggestion
        UserNotification.error(`Loading Data Nodes failed with status: ${errorThrown}`,
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
> +          'Could not load data nodes');
```suggestion
          'Could not load Data Nodes');
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesClusterPage.tsx
> +        Graylog data nodes offer a better integration with Graylog and simplify future updates. They allow you to index and search through all the messages in your Graylog message database.
```suggestion
        Graylog Data Nodes offer a better integration with Graylog and simplify future updates. They allow you to index and search through all the messages in your Graylog message database.
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesClusterPage.tsx
> +                  title: 'Data nodes documentation',
```suggestion
                  title: 'Data Nodes documentation',
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesClusterPage.tsx
> +  <DocumentTitle title="Data nodes Cluster">
```suggestion
  <DocumentTitle title="Data Nodes Cluster">
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesClusterPage.tsx
> +    <PageHeader title="Data nodes Cluster"
```suggestion
    <PageHeader title="Data Nodes Cluster"
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
> +  <DocumentTitle title="Data nodes Migration">
```suggestion
  <DocumentTitle title="Data Nodes Migration">
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
> +    <PageHeader title="Data nodes Migration"
```suggestion
    <PageHeader title="Data Nodes Migration"
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
> +                  title: 'Data nodes documentation',
```suggestion
                  title: 'Data Nodes documentation',
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
> +        Graylog data nodes offer a better integration with Graylog and simplify future updates. They allow you to index and search through all the messages in your Graylog message database.
```suggestion
        Graylog Data Nodes offer a better integration with Graylog and simplify future updates. They allow you to index and search through all the messages in your Graylog message database.
```

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesPage.tsx
>                    title: 'Data Nodes documentation',
Spelling already correct.

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/pages/DataNodesPage.tsx
>      <PageHeader title="Data Nodes"
Spelling already correct.

2023-12-19 17:46 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodePageNavigation.tsx
> +  { title: 'Data Nodes', path: Routes.SYSTEM.DATANODES.LIST, exactPathMatch: true },
Spelling already correct.

2023-12-20 09:29 UTC, grotlue reviewed
Two more places for the spelling. I will just commit those suggestions, that will make it easier :)

Also It would be good if we can still "fix":
❌ The action "Rejoin" should only be shown for removed data nodes
❌ The action "Remove" should only be for data nodes that are not already removed

2023-12-20 09:29 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
> +    dialogTitle: 'Rejoin Data node',
```suggestion
    dialogTitle: 'Rejoin Data Node',
```

2023-12-20 12:36 UTC, grotlue approved these changes
Looking great! Thanks a lot!

✅ The action “Rejoin” should only be shown for removed data nodes
✅ The action “Remove” should only be for data nodes that are not already removed

2023-12-21 09:15 UTC, merged