Move pull request string extraction to gpi
Graylog2/graylog2-server pull request #17319
Opened 2023-11-15 14:51 UTC by mpfz0r

/nocl

2023-11-15 15:23 UTC, bernd requested changes

2023-11-15 15:23 UTC, bernd commented on graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
> -# Instant archiving is disabled by default
Unrelated change.

2023-11-15 17:27 UTC, mpfz0r commented on graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
> -# Instant archiving is disabled by default
ah. dang

2023-11-16 14:38 UTC, bernd approved these changes

2023-11-17 10:00 UTC, merged