Add datanode cluster metrics and dashboard
Graylog2/graylog2-server pull request #18066
Opened 2024-01-26 15:46 UTC by moesterheld

/nocl

/prd Graylog2/graylog-plugin-enterprise#6478

## Description
Records data node cluster metrics to metrics data stream and provides the dashboard to show them

## Motivation and Context
fixes https://github.com/Graylog2/graylog2-server/issues/17704

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

2024-02-02 14:19 UTC, grotlue requested changes
While testing I came across some points which I find confusion and I think the user would too:

❌ The footer (showing the current Graylog version) is shown twice

❌ The dashboard title is `datanodes`, the in the summary and description it's data nodes. It;s stick to Data Nodes.
❓Does the dashboard title, summary and description need to be editable?
❓Is it necessary that the user can mark the dashboard as favorite, even though it does not have any real functionality?
❌ Some buttons are not usable, e.g. widget edit button. When I click them they redirect to "empty pages" with is a weird behaviour. When I click the browser back button on those empty pages I am back on the *Data Nodes* tab, not *Cluster Management*
❌ It is possible to save this dashboard as a new dashboard using the same title. It will then also appear in the dashboard list as usual. However, obviously it's a different dashboard, so going back to the DataNode Cluster Metrics I see the "old" version of the dashboard - at least that is how the user could perceive it.

2024-02-02 14:19 UTC, grotlue commented on changelog/unreleased/issue-17704.toml
> +type = "fixed"
It's a new feature, no bugfix, right?

2024-02-02 14:19 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/ClusterManagement/ClusterManagementTeaserSearch.tsx
> +    description: 'Show performance metrics of your data node and managed OpenSearch cluster.',
```suggestion
    description: 'Show performance metrics of your Data Node and managed OpenSearch cluster.',
```

2024-02-07 09:04 UTC, grotlue approved these changes
Looking good, thank you for the changes!

2024-02-08 11:07 UTC, todvora approved these changes
LGTM, awesome work!

2024-02-08 11:10 UTC, merged