Only leader drops outdated nodes
Graylog2/graylog2-server pull request #18080
Opened 2024-01-29 14:58 UTC by luk-kaminski

## Description
Fixes #18078
/nocl

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-01-29 16:22 UTC, bernd commented
@luk-kaminski Please carefully test with a Graylog cluster if this has any negative consequences when there is no leader for like one minute and nodes disappear in that time frame. There might be errors regarding metrics requests and maybe others.

2024-01-29 16:43 UTC, bernd requested changes
Elaborating on the one-minute example I mentioned in [my earlier comment](https://github.com/Graylog2/graylog2-server/pull/18080#issuecomment-1915061469):

Our leader election is using MongoDB TTL indices. A background job in MongoDB deletes documents with an expired TTL index. That job runs every 60 seconds. It might run later when the database load is high.

> The background task that removes expired documents runs every 60 seconds. As a result, documents may remain in a collection during the period between the document's expiration and the running of the background task. MongoDB starts deleting documents 0 to 60 seconds after the index completes.

> Because the duration of the removal operation depends on the workload of your [mongod](https://www.mongodb.com/docs/manual/reference/program/mongod/#mongodb-binary-bin.mongod) instance, expired data may exist for some time beyond the 60 second period between runs of the background task.

*Source:* https://www.mongodb.com/docs/manual/core/index-ttl/#delete-operations

That means a new leader election can take at least 60 seconds when the leader node disappears without a clean shutdown.

We know that our node expiry system is not optimal, but our system currently relies on nodes disappearing quickly from MongoDB's `nodes` collection.
We need to consider all the consequences when unreachable nodes stay in the collection longer.

I currently tend to leave this mechanism as it is for now and think about a better version of our node management for a future release.

2024-01-30 08:01 UTC, luk-kaminski commented
Hi @bernd,
I understand that if only the leader is responsible for nodes removal from the `nodes` collection, the entries for old nodes may stay longer in that collection in some circumstances.

But that leads to another question: what kind of problem does it cause if we have an entry for old node staying longer in that collection?

Why I am asking: there is an explicit config setting, called `stale_leader_timeout`, that allows to prolong that delay, allows to keep entries for old nodes longer in the collection. If it is a problem, should we allow it to be changed, increased? If it is not a problem, then should we bother about entries staying in collection for around 60 sec. ?

2024-01-30 09:21 UTC, bernd commented
@luk-kaminski 

> But that leads to another question: what kind of problem does it cause if we have an entry for old node staying longer in that collection?

That's what we need to find out before we change the node expiration mechanism. :slightly_smiling_face: 



> Why I am asking: there is an explicit config setting, called `stale_leader_timeout`, that allows to prolong that delay, allows to keep entries for old nodes longer in the collection. If it is a problem, should we allow it to be changed, increased? If it is not a problem, then should we bother about entries staying in collection for around 60 sec. ?

The `stale_leader_timeout` config option has a misleading name. In the `AbstractNodeService`, the field is called `pingTimeout`. That would have been a better name for the config option. :smile: 

The `stale_leader_timeout` is the number of milliseconds we wait until we remove a node from MongoDB's `nodes` collection. It's unrelated to the MongoDB TTL index that we use for leader elections.

We never really changed the default value of the ping timeout (`stale_leader_timeout`), that's why we are super careful about touching the node expiration mechanism without more research and testing.

2024-01-30 12:02 UTC, luk-kaminski commented
@bernd - we have clients that started changing `stale_leader_timeout` by themselves. Let's have this discussion on slack instead of GH.

2026-01-27 09:48 UTC, closed without merging