Fix text color for button in active state
Graylog2/graylog2-server pull request #18835
Opened 2024-03-27 14:40 UTC by grotlue

## Description
Fixes: https://github.com/Graylog2/graylog2-server/issues/18806

The text color for the button when the prop `active={true}` was not readable in light mode. 
I added some styles to make sure that it works in all variants in both themes, find an example screenshot below.

![Screenshot 2024-03-27 at 15 37 01](https://github.com/Graylog2/graylog2-server/assets/3169354/36aa3341-9c7e-49d6-8fe8-bc63419af827)
![Screenshot 2024-03-27 at 15 37 06](https://github.com/Graylog2/graylog2-server/assets/3169354/6cf0c72d-5fd3-4bc7-91b3-3ad604bc2275)

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-03-28 09:52 UTC, ousmaneo approved these changes
Tested and the change for the button colors works!

2024-03-28 12:17 UTC, patrickmann requested changes
Still just seeing a single button ... blocking merge until we understand why.

2024-04-02 08:07 UTC, grotlue commented
The options we see are configurable. In the test environment, we only have `Delete` configured. Usually, we have three options to choose from.

2024-04-02 08:13 UTC, patrickmann approved these changes

2024-04-02 08:13 UTC, merged