Configure forbiddenapis for jetbrains annotations
Graylog2/graylog2-server pull request #19029
Opened 2024-04-12 06:01 UTC by todvora

/nocl

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-04-15 10:23 UTC, thll requested changes
Thanks for the initiative!

`jakarta.validation.constraints.NotNull` is used for bean validation. We shouldn't use it to replace `org.jetbrains.annotations.NotNull`.

We should use `jakarta.annotation.Nonnull` instead.

2024-04-15 10:23 UTC, thll commented on pom.xml
> +                            org.jetbrains.annotations.NotNull @ Use jakarta.validation.constraints.NotNull
```suggestion
                            org.jetbrains.annotations.NotNull @ Use jakarta.annotation.Nonnull
```

2024-04-15 12:57 UTC, todvora commented on pom.xml
> +                            org.jetbrains.annotations.NotNull @ Use jakarta.validation.constraints.NotNull
Thanks, good point, let me change it.

2024-04-16 07:43 UTC, todvora commented
@thll There are still many javax.annotation.Nullable and javax.annotation.Nonnull annotations, which we could replace as well. But rather in a different PR, to avoid mixing too many things together.

2024-04-17 14:57 UTC, thll commented
> @thll There are still many javax.annotation.Nullable and javax.annotation.Nonnull annotations, which we could replace as well. But rather in a different PR, to avoid mixing too many things together.

@todvora I agree. Let's focus on the jetbrains annotations here.

2024-04-18 09:42 UTC, merged