Datanode remote reindex migration UI features
Graylog2/graylog2-server pull request #19100
Opened 2024-04-18 11:28 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/18876

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-05-03 06:44 UTC, todvora reviewed
Everything works fine, there is just one strange thing. Notice the selected indices counter, saying 3/11

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/c8ed0ffe-1d40-4576-b6c1-95cc1a75e129)

Now I use the search feature and the counter displays selected counter only for the filtered results. I'd expect it to still show the overall number of selected/all, not just data for the filtered view.

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/f3834570-b049-4848-971f-2624028e3d22)

2024-05-06 09:57 UTC, todvora approved these changes
LGTM! Thank you!

2024-05-06 14:58 UTC, moesterheld approved these changes
lgtm.
just one comment with a possible cosmetic change. could we change the color for log messages with log_level error to a light red and warnings to e.g. yellow?

2024-05-07 07:54 UTC, ousmaneo requested changes
It looks good; I added some small comments inline.

2024-05-07 07:54 UTC, ousmaneo commented on graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
> +      <BootstrapModalWrapper showModal={showLogView}
```suggestion
   {showLogView &&  <BootstrapModalWrapper showModal={showLogView}
```

2024-05-07 07:54 UTC, ousmaneo commented on graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
> +            ) : ('<no logs>')}
```suggestion
            ) : ('No logs.')}
```

2024-05-07 13:44 UTC, ousmaneo approved these changes
LGTM!

2024-05-07 14:48 UTC, merged