remove unnecessary steps/big texts/unavailable paths
Graylog2/graylog2-server pull request #19312
Opened 2024-05-10 11:31 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/19229

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-05-17 08:10 UTC, moesterheld requested changes

2024-05-17 11:18 UTC, moesterheld commented
> 2. Hostname and allowlist are not pre-filled in remote-reindexing

@gally47 I have made a wrong assumption when providing the host/allowlist value. This will only be available with https://github.com/Graylog2/graylog2-server/issues/19383

2024-05-21 10:58 UTC, ousmaneo approved these changes
Frontend looks good !

2024-05-21 12:22 UTC, todvora approved these changes
Tested locally, looks good to me! Thanks!

2024-05-21 12:56 UTC, merged