Add modal to select index template on index creation
Graylog2/graylog2-server pull request #19381
Opened 2024-05-17 10:17 UTC by grotlue

## Description
Part of: https://github.com/Graylog2/graylog2-server/issues/19075

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-06-06 07:56 UTC, ousmaneo requested changes
Tested and looks good.
I added some comments inline, a part from that it's good to go.

2024-06-06 07:56 UTC, ousmaneo commented on graylog2-web-interface/src/components/indices/data-tiering/DataTieringVisualisation.tsx
> +  ${value > 20
We should move this value to a constant since we reuse it in many places.

2024-06-06 07:56 UTC, ousmaneo commented on graylog2-web-interface/src/components/indices/IndexSetTemplates/SelectIndexSetTemplateModal.tsx
> +    }, { enabled: true },
We can add the default value `enabled = true`  to `useTemplates`, so we add the param only when we want to disable it.

2024-06-06 07:56 UTC, ousmaneo commented on graylog2-web-interface/src/components/indices/IndexSetTemplates/TemplateDetails.tsx
We should add an Edit button to the template details page.
![image](https://github.com/Graylog2/graylog2-server/assets/1381455/e2e29516-daf0-47b0-aa44-5ae25e5ce68e)

2024-06-11 09:57 UTC, patrickmann approved these changes
Backend looks good

2024-06-12 14:30 UTC, ousmaneo approved these changes
Tested and looks good!

2024-06-12 14:48 UTC, merged