Datanode UI fixes
Graylog2/graylog2-server pull request #19539
Opened 2024-06-03 14:37 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/19477
fixes https://github.com/Graylog2/graylog2-server/issues/19467

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-06-07 15:43 UTC, vvasylenko approved these changes

2024-06-12 12:47 UTC, grotlue requested changes
Code-wise looking good, just one small comment.

Note: I didn't test it as I saw that it's already tested.

2024-06-12 12:47 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
> +  margin-top: 20px;
I think we should try to use `spacings` variables from our `theme`.

2024-06-12 14:20 UTC, grotlue approved these changes

2024-06-12 15:21 UTC, merged