Extract pipeline resolving code into a reusable class
Graylog2/graylog2-server pull request #19602
Opened 2024-06-11 18:29 UTC by bernd

- Introduce a reusable PipelineResolver class that doesn't depend on the database
- Make the rule, pipeline, and stage metric prefix configurable

/nocl Internal refactoring

2024-06-13 22:11 UTC, danotorrey approved these changes
This regression tests with Illuminate processing and with a standard simple pipeline test successfully. The code looks good from what I can see, but it would be good to get one more review.

2024-06-14 06:21 UTC, thll approved these changes
LGTM

2024-06-14 07:10 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineResolverConfig.java
> +import static com.google.common.base.Strings.isNullOrEmpty;
Good catch, thank you!

2024-06-14 09:19 UTC, bernd commented
Thanks for the reviews! I am moving it to draft again to fix the issue with metrics registration and removal.

Both are done in different places now which is confusing.

2024-06-17 08:24 UTC, bernd commented
@danotorrey @thll The PR is ready for review again. I extracted the metrics registration and removal into a separate class.

2024-06-17 22:37 UTC, danotorrey approved these changes
LGTM and tests successfully with the latest

2024-06-18 12:34 UTC, thll requested changes

2024-06-18 14:45 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineResolver.java
> +    public record Result(MetricRegistry metrics, ImmutableMap<String, Pipeline> pipelines) {}
Good catch! I removed it.

2024-06-19 07:53 UTC, thll approved these changes

2024-06-19 08:11 UTC, merged