Make migration thread count counfigurable
Graylog2/graylog2-server pull request #19794
Opened 2024-07-01 17:04 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/19792

## Screenshots (if appropriate):
![Screenshot 2024-07-01 at 19 04 09](https://github.com/Graylog2/graylog2-server/assets/106236152/95e8f8be-b0d6-45a0-a902-834275e5fb24)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-07-04 15:36 UTC, moesterheld requested changes
Works in general. Thank you for adding.
However, I cannot remove the value in the input field using the keyboard/mouse, I can only add to it.
Also, one small textual change.

2024-07-04 15:36 UTC, moesterheld commented on graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
> +                 help="Threads count defines how many indices will be migrated parallelly (minimum 1, default 4)"
```suggestion
                 help="Threads count defines how many indices will be migrated in parallel (minimum 1, default 4)"
```

2024-07-08 10:11 UTC, gally47 commented
> Works in general. Thank you for adding. However, I cannot remove the value in the input field using the keyboard/mouse, I can only add to it. Also, one small textual change.

@moesterheld the value is not supposed to be removed you can only replace the default value (4) with any positive integer.

2024-07-08 10:24 UTC, moesterheld commented
> > Works in general. Thank you for adding. However, I cannot remove the value in the input field using the keyboard/mouse, I can only add to it. Also, one small textual change.
> 
> @moesterheld the value is not supposed to be removed you can only replace the default value (4) with any positive integer.

yep. never mind, I retried it and it behaves consistently with all other numeric input fields in Graylog. 
I wanted to double click the input and write another value into it, however it didn't select the value so I could directly replace it. Also, backspace won't work, which feels a little weird. I think the behavior of the numeric input could be improved in general, but it's ok for now.

2024-07-08 10:24 UTC, moesterheld approved these changes

2024-07-08 10:59 UTC, ousmaneo approved these changes
It works as expected. I have a small comment.

2024-07-08 10:59 UTC, ousmaneo commented on graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
> +      value = Number(e.target.value) < 1 ? DEFAULT_THREADS_COUNT : Number(e.target.value);
We could use the `getValueFromInput` from the `FormUtils`.

2024-07-09 07:55 UTC, todvora approved these changes
LGTM!

2024-07-09 07:55 UTC, merged