Add stream destination output filters UI
Graylog2/graylog2-server pull request #19846
Opened 2024-07-08 08:36 UTC by ousmaneo

This PR adds the Filter output UI to allow the filter to be added to the Stream destination outputs using the Rule Builder.

- List filters
- CRUD on filters

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-07-08 16:24 UTC, gally47 requested changes
Looking good. Found some nitpicks.

Ithink we should improve the icons size and margins here:
![Screenshot 2024-07-08 at 18 21 41](https://github.com/Graylog2/graylog2-server/assets/106236152/e9176256-487a-4a22-bef4-42da675c9302)

2024-07-08 16:24 UTC, gally47 commented on graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRulesFields.tsx
> +    margin: 0 8px;
can we use theme spacing here too?

2024-07-08 16:24 UTC, gally47 commented on graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingProcessing.tsx
>    margin-right: 6px;
can we use theme spacing here?

2024-07-09 15:59 UTC, grotlue requested changes
I have some comments for the code, but those are all small things.
In general if there is time, it would be nice to add PropTypes, but this is not crucial.

## Test Result
❌ maybe not related to this PR but still wanted to document it: stream list status button is too big for data warehouse items
![Screenshot 2024-07-09 at 17 27 01](https://github.com/Graylog2/graylog2-server/assets/3169354/455bd532-2fc5-499c-b04f-983d6431d99d)

❌ buttons for output actions are misaligned
![Screenshot 2024-07-09 at 17 29 48](https://github.com/Graylog2/graylog2-server/assets/3169354/c99e90b5-a092-4942-b8fe-710b227b2b61)


❌ In rule modal, without any rule, when clicking on the radio button AND or OR I get the following error
![Screenshot 2024-07-09 at 17 32 26](https://github.com/Graylog2/graylog2-server/assets/3169354/7d950207-a2ce-4221-9b82-836ddd24258a)

❌ no default value for AND/OR radio button in rule modal

❌ When enabling an existing rule in the modal or creating a new enabled rule I get the following error
![Screenshot 2024-07-09 at 17 35 53](https://github.com/Graylog2/graylog2-server/assets/3169354/88b7d727-18e2-4fc1-80d1-6f04608e3ded)

❌ Creating a new rule in the modal, with "Enable Rule" checked first, there is no text shown for added conditions
![Screenshot 2024-07-09 at 17 36 32](https://github.com/Graylog2/graylog2-server/assets/3169354/aee71149-0741-4677-a2ed-7d1a87bab7e6)

❌ Searching the rule list is not working
![Screenshot 2024-07-09 at 17 43 05](https://github.com/Graylog2/graylog2-server/assets/3169354/921ec285-ac46-403a-bced-28459b1972ca)

**Suggestions for improvements:**
- I think it would be nice to show the rule description in the rule list
- I think it would be nice to show the rule enabled state in the rule list

⚠️ Due to not being able to enable rules I couldn't test if they are applied to the Stream

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterDeleteButton.tsx
> +                     onConfirm={async () => {
nit: could be extracted into a handler.

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterDeleteButton.tsx
> +  const [showDialog, setShowDialog] = useState(null);
Why not use `false` as a default value?

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleEditButton.tsx
> +      queryClient.invalidateQueries(['streams']);
This could also be moved to the queries itself, assuming we always want to update this.

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/hooks/useStreamOutputFilters.ts
> +    `/streams/${streamId}/destinations/filters`,
Nit: we could move this into `ApiRoutes`.

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/hooks/useStreamOutputRuleMutation.ts
> +      UserNotification.error(`Create stream output filter rule failed with status: ${errorThrown}`,
```suggestion
      UserNotification.error(`Creating stream output filter rule failed with status: ${errorThrown}`,
```

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/hooks/useStreamOutputRuleMutation.ts
> +      UserNotification.error(`Updating strean output filter rule failed with status: ${errorThrown}`,
```suggestion
      UserNotification.error(`Updating stream output filter rule failed with status: ${errorThrown}`,
```

2024-07-09 15:59 UTC, grotlue commented on graylog2-web-interface/src/components/streams/hooks/useStreamOutputRuleMutation.ts
> +      UserNotification.success(' Stream Output filter rule has been successfully removed.', 'Success!');
```suggestion
      UserNotification.success('Stream Output filter rule has been successfully removed.', 'Success!');
```

2024-07-10 09:08 UTC, ousmaneo commented
> ⚠️ Due to not being able to enable rules, I couldn't test if they are applied to the Stream

The enabled props were present on the API specs but not implemented in the API, so I removed it

2024-07-10 10:17 UTC, grotlue requested changes
Thanks for the changes! Code looks good now, I have a few small findings.

❌ Description column is lowercase
![Screenshot 2024-07-10 at 12 05 41](https://github.com/Graylog2/graylog2-server/assets/3169354/30d21d65-b8e3-43f5-a400-83df78587e11)

❌ The rule _check if value is in array_ is somehow not working, it will show this error when I use a string or array with strings. Maybe the rule is broken in general. I would expect this error in validation at least.
![Screenshot 2024-07-10 at 11 58 55](https://github.com/Graylog2/graylog2-server/assets/3169354/48314fb6-a1e1-49c4-91c0-4ad3bed4d7e7)

❌ Not a bug, but the whole rule modal is validated when I e.g. add a title or simply change from _AND_ to _OR_. Then all following fields are marked red even before touching them. That looks like everything is broken, I think it would be good to validate  rules when touching their fields or after adding them.

https://github.com/Graylog2/graylog2-server/assets/3169354/2921b225-ccb8-4750-b4b9-a047bf976a82

2024-07-10 15:52 UTC, merged