dd data node hep check and notification
Graylog2/graylog2-server pull request #20168
Opened 2024-08-13 11:33 UTC by moesterheld

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-08-13 11:38 UTC, moesterheld commented
@todvora do you have a better idea for determining when to trigger the notification or do you think this mechanism will do?

2024-08-14 16:27 UTC, tellistone commented
I think that will work nicely. The notification might recommend the specific remediation, set the HEAP to almost 50% (47% ?) of total memory of the host (that is what AWS Opensearch auto-tune does)

2025-03-19 07:32 UTC, todvora requested changes

2025-03-19 07:32 UTC, todvora commented on data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java
> +            return osBean.getFreeMemorySize() - buffer;
This computation leads on my machine to negative value.  It doesn't break the logic, but feels wrong to operate with negative free memory values. Should we return zero if the free memory is lower than buffer?

![image](https://github.com/user-attachments/assets/fca336bc-5fd7-4ef6-9ee1-3eaa5549533d)

2025-04-14 09:06 UTC, moesterheld commented on data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java
> +            return osBean.getFreeMemorySize() - buffer;
I switched to using oshi for determining the memory. Can you recheck if this works?

2025-04-15 07:15 UTC, todvora commented on data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java
> +            return osBean.getFreeMemorySize() - buffer;
It works now for me and delivers reasonable, positive numbers.

Is the usage of non floating-point arithmetic a deliberate decision? 

```
long memoryRatio = freeMemory / heapBytes;
```

![image](https://github.com/user-attachments/assets/10a6eae2-3c1f-482a-aba9-da6823191817)

2025-04-15 08:36 UTC, moesterheld commented on data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java
> +            return osBean.getFreeMemorySize() - buffer;
Good catch. God, I hate math in Java 😉

2025-04-23 13:19 UTC, todvora reviewed
The floating point arithmetic is now working fine. But it brings other challenges. Do we really want to include the exact floating point ratio in the notification?

![image](https://github.com/user-attachments/assets/0a41dc03-2b07-4eb7-b4ab-e5ef9ac40e23)

I'd suggest rounding it down to one decimal place.

2025-04-23 16:16 UTC, tellistone commented
Perhaps round it  to one decimal place.

We should change the copy of the notification to be more perspective IMO.

Eg. This data node only has 1GB Java Heap assigned, out of a total of 16GB RAM. For production performance, please configure this node to use 8 GB HEAP (50% of RAM).

2025-04-25 09:11 UTC, tellistone commented
Thanks - might be also worth putting line breaks between the three sections of copy so its easier to read

2025-04-25 11:22 UTC, todvora approved these changes
LGTM!

2025-04-25 12:43 UTC, moesterheld commented
> Thanks - might be also worth putting line breaks between the three sections of copy so its easier to read

Added paragraphs to make it more readable

2025-04-28 07:33 UTC, merged