Datanode migration telemetry
Graylog2/graylog2-server pull request #20225
Opened 2024-08-20 15:14 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/20086

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-09-05 09:15 UTC, grotlue requested changes
Looks good in general, some small suggestions.
I haven't tested it yet, but as it is telemetry it should be good.

2024-09-05 09:15 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAConfiguration.tsx
> +    sendTelemetry((e?.target?.innerText === 'Upload CA')
Would be nice to move `Upload CA` into a constant and reuse it at line 63 to avoid bugs.

2024-09-05 09:15 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/migrations/ManualMigrationStep.tsx
> +      event_details: { migration_type: (step === 'SELECT_ROLLING_UPGRADE_MIGRATION') ? 'IN-PLACE' : 'REMOTE REINDEX' },
Same here, constant for the step would be nice.

2024-09-05 09:15 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
> +import useMigrationState from '../../hooks/useMigrationState';
```suggestion
import useMigrationState from 'components/datanode/hooks/useMigrationState';
```

2024-09-05 09:15 UTC, grotlue commented on graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
> +    case 'MIGRATION_WELCOME_PAGE':
Same for these, constants and reusing them.

2024-09-06 10:05 UTC, grotlue approved these changes
Thank you for the changes, looks good!

2024-09-06 11:00 UTC, ousmaneo approved these changes
Tested and looks good!

2024-09-06 12:59 UTC, merged