Remote Reindex UI improvements
Graylog2/graylog2-server pull request #20237
Opened 2024-08-21 12:35 UTC by gally47

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-08-28 09:14 UTC, todvora approved these changes
Tested locally and everything works as expected. One more detail - could we make the hostname mandatory? 
 
![image](https://github.com/user-attachments/assets/3cf6a256-749d-47b8-86a3-4a8bca1af07b)

Thx!

2024-09-04 06:44 UTC, ousmaneo approved these changes
LGTM !

2024-09-06 08:41 UTC, ousmaneo requested changes
Looks good, I added a small comments

2024-09-06 08:41 UTC, ousmaneo commented on graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
> +                                               disabled={Object.values(errors).length > 0}
We can use `isValidating` and `isValid` from formik to disable the button

2024-09-06 08:48 UTC, ousmaneo approved these changes

2024-09-06 10:11 UTC, merged