Display migration error message in RemoteReindexRunning step
Graylog2/graylog2-server pull request #20527
Opened 2024-09-24 10:52 UTC by gally47

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/20461

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-10-04 13:03 UTC, grotlue approved these changes
Code looks good 👍

2024-10-04 14:18 UTC, moesterheld requested changes
Looks good, however even https://github.com/Graylog2/graylog2-server/pull/20622 doesn't return the `error_message` yet, but only displays the ERROR status in the progress bar. I would assume, the error would then be passed in the triggerStep
Looks like this needs to be worked on together with backend to provide a working solution.

2024-10-07 13:06 UTC, todvora commented
The RemoteReindexMigration DTO provides a field called "error", which will be extracted from the migration progress. I'd recommend using this field. Even better would be to filter logs for errors and display all of them in the error box. We can filter them by severity, either in the backend or in the frontend.

2025-04-14 09:52 UTC, moesterheld approved these changes
As discussed, we should merge this in this state and make additional changes if we continue working on the remote reindexing

2025-04-15 07:37 UTC, merged