Centralized view of Graylog cluster components
Graylog2/graylog2-server pull request #21058
Opened 2024-11-26 15:47 UTC by gally47

New Cluster page that presents all currently active nodes used in the Graylog deployment. There could be options for a table view and a more graphical cluster view.

## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/20997

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2025-03-05 13:09 UTC, ousmaneo commented on graylog2-web-interface/src/components/cluster-configuration/ClusterActions.tsx
> +const ClusterActions = ({ node }: Props) => {
We should add a test for the Actions.

2025-03-05 13:14 UTC, ousmaneo commented on graylog2-web-interface/src/components/cluster-configuration/ClusterConfigurationGraphView.tsx
> +const ClusterConfigurationGraphView = () => (
Since we haven't implemented the card view yet, we should remove it for now.

2025-03-05 13:29 UTC, ousmaneo commented on graylog2-web-interface/src/pages/ClusterConfigurationPage.tsx
> +              {viewType === 'cards' && (
We should remove the card view here too

2025-03-05 13:30 UTC, ousmaneo commented on graylog2-web-interface/src/pages/ClusterConfigurationPage.tsx
> +          {false && (
We should also remove the menu since we don't use it

2025-03-05 13:33 UTC, ousmaneo commented on graylog2-web-interface/src/components/cluster-configuration/ClusterConfigurationListView.tsx
> +      {clusterNodes.graylogNodes.map((graylogNode) => (
When loading the page, the list is empty for a bit while waiting for the API response. We should show a Loader to let users know that something’s happening. 
![cluster overview](https://github.com/user-attachments/assets/1867fd66-a475-456d-970f-4edccf9a0076)

2025-03-05 13:48 UTC, ousmaneo commented on graylog2-web-interface/src/pages/ClusterConfigurationPage.tsx
> +            <TableFetchContextProvider refetch={clusterNodes.refetchDatanodes} searchParams={searchParams} attributes={[]}>
Since we want to show the Graylog and data-node nodes on a single page, we should create a proper endpoint that handles the entities. That way, we can use the EntityDataTable and have pagination and other cool features. Is that something you’re planning?

2025-03-05 14:11 UTC, moesterheld requested changes
Looks good, I like it. However, I think we need to add the data node roles to the data node endpoint. Looks like they are hardcoded right now

2025-03-05 14:35 UTC, gally47 commented on graylog2-web-interface/src/pages/ClusterConfigurationPage.tsx
> +            <TableFetchContextProvider refetch={clusterNodes.refetchDatanodes} searchParams={searchParams} attributes={[]}>
Yes that's the end goal: to have a proper endpoint for all the cluster's nodes that includes also MongoDB instances, forwarders and maybe also sidecars, but for this cycle the goal was the visual (frontend part) of a centralized Cluster Configuration page only. We will likely add that endpoint next cycle.

2025-03-05 15:26 UTC, gally47 commented
> Tested and looks good! I added some comments inline.
> 
> In the previous node page, we had information about the node's metrics and JVM details for each node. However, those details seem to be missing in the new Cluster page. Do you think they’ll be added later? ![image](https://private-user-images.githubusercontent.com/1381455/419482312-0a0eea73-d309-4f8d-adf1-923d9b8e00f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExODc4MzYsIm5iZiI6MTc0MTE4NzUzNiwicGF0aCI6Ii8xMzgxNDU1LzQxOTQ4MjMxMi0wYTBlZWE3My1kMzA5LTRmOGQtYWRmMS05MjNkOWI4ZTAwZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMDVUMTUxMjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjdhMDEwOTZkZjU5Y2Q0NGRlNzcwYTgyYjU0OTNiODFhMGU0NjJjYjEyNGU0OTNlYTBhNGM4NTNhMTBmYmUyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6_RwXG1_IZYg8n13SpWm0jWc1fSYqyK2EYu89om4Nuw)

Yes we are aware of that, @sethgraylog's idea was to keep the centralized cluster nodes page simple, we only show the node's status for metrics and JVM details they can navigate to the details page.

2025-03-07 09:39 UTC, ousmaneo approved these changes
LGTM!

2025-03-07 09:41 UTC, ousmaneo approved these changes

2025-03-10 07:35 UTC, todvora approved these changes
LGTM! Thanks!

2025-03-10 09:07 UTC, merged