Update dwh types
Graylog2/graylog2-server pull request #21077
Opened 2024-11-29 06:31 UTC by ousmaneo

Update dwh types

/nocl
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-12-06 14:56 UTC, gally47 requested changes
Looking good, can we add unit tests for the main components? I also added some comments below.

2024-12-06 14:56 UTC, gally47 commented on graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
> +                <LinkContainer to={Routes.SYSTEM.INDEX_SETS.SHOW(indexSet?.id)}>
Should we disable the link in case indexSet `undefined`?

2024-12-11 09:47 UTC, kodjo-anipah approved these changes
LGTM check enterprise pr for what was tested

2024-12-11 10:16 UTC, gally47 approved these changes

2024-12-11 14:02 UTC, grotlue approved these changes
Frontend code looks good!

2024-12-11 16:04 UTC, merged