Datanode/opensearch configuration beans
Graylog2/graylog2-server pull request #21082
Opened 2024-11-29 18:08 UTC by todvora

/nocl

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-12-10 17:27 UTC, moesterheld requested changes
Awesome work. I haven't finished thorough testing of the PR yet, but here are already some code comments.

2024-12-10 17:27 UTC, moesterheld commented on data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java
> -            final Set<String> current = nodeService.allActive().values().stream().map(DataNodeDto::getClusterAddress).filter(Objects::nonNull).collect(Collectors.toSet());
nodeService can be removed from class

2024-12-11 09:43 UTC, todvora commented on data-node/src/main/java/org/graylog/datanode/bindings/OpensearchProcessBindings.java
> +        opensearchConfigurationBeanMultibinder.addBinding().to(OpensearchCommonConfigurationBean.class).asEagerSingleton();
Thanks, fixed!

2024-12-11 11:48 UTC, moesterheld commented on data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/files/ConfigFile.java
> +public interface ConfigFile {
Actually, I meant moving the `ConfigFile` interface and implementing classes out of the opensearch package. But we can also do this when reusing them for trino.

2024-12-11 12:35 UTC, todvora commented on data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/files/ConfigFile.java
> +public interface ConfigFile {
Makes sense, just pushed the change. It now lives under `org.graylog.datanode.process.configuration`, which feels quite correct.

2024-12-12 09:31 UTC, moesterheld approved these changes
lgtm now. Thank you again for the massive change.

2024-12-12 09:32 UTC, merged

2024-12-12 09:56 UTC, todvora commented
Thank you for reviewing, testing and merging! Massive task as well!