Handle system index set scoping
Graylog2/graylog2-server pull request #21174
Opened 2024-12-12 10:25 UTC by patrickmann

Resolves Graylog2/graylog-plugin-enterprise#5904

#21148 introduced scoping for index sets. We now need to make sure scope is accounted for.

## Description

- ensure that all system index sets have scope set to `SystemIndexSetScope`
- use scope-aware methods for write operations on index sets

## Motivation and Context

See linked issue

## How Has This Been Tested?

- first migration runs successfully
- multiple migrations 
- system index sets cannot be deleted
- regular index sets can be deleted

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2025-02-18 12:30 UTC, kroepke reviewed
Could we please review the proliferation of scopes?
It was meant as a way to mark specific entities as "system" vs "user" and not as a generic tagging system.
If we now add a scope for every entity, in code, we are essentially turning this into a very cumbersome tagging system.

As it stands, I cannot see the point of adding individual scopes, if all we use them for is visibility and whether users can edit them.
I'd greatly prefer to unify the recently added scopes into a single system scope, unless there's a good reason to have them separate.
Thanks!

2025-02-18 13:10 UTC, patrickmann commented
Good to know. Some javadoc in e.g. `EntityScopes` would go a long way towards ensuring they are used as intended.

Moving this back to draft status then, to make that change.

2025-02-26 14:01 UTC, patrickmann commented
Note: this PR is conflicting with #21762, which is still working with `SystemPipelineScope`. One or the other will need to be modified, depending which is merged first.

2025-03-03 16:33 UTC, kodjo-anipah requested changes
Would be nice to have a follow up ticket so that we can rework parts of this and actually throw the correct error msg on api levl

2025-03-03 16:33 UTC, kodjo-anipah commented on graylog2-server/src/main/java/org/graylog2/migrations/V20241212102900_ScopeMigration.java
> +                                Filters.eq(FIELD_REGULAR, false),
Should be fine illuminate sets their index set as regular: 
https://github.com/Graylog2/graylog-plugin-enterprise/blob/485e439171a024b825266aca6e4883914b6ca1e9/enterprise/src/main/java/org/graylog/plugins/illuminate/installation/BundleInstaller.java#L420
@kingzacko1, we are not missing any special case here, right?

2025-03-04 07:44 UTC, patrickmann commented
> Would be nice to have a follow up ticket so that we can rework parts of this and actually throw the correct error msg on api level

I'm not convinced we need to make the API any "friendlier" here. 
- The exception already has an appropriate detail message, e.g. "Non-deletable entity cannot be deleted".
- Generally we have scope checks in the UI to gray out illegal actions, so the API exception would only show when these fail or are missing.

2025-03-04 08:11 UTC, kodjo-anipah commented on graylog2-server/src/main/java/org/graylog2/migrations/V20241212102900_ScopeMigration.java
> +    public V20241212102900_ScopeMigration(ClusterConfigService configService, MongoCollections mongoCollections) {
One last thing: can we change the migration name, currently it dates back to last year

2025-03-04 08:33 UTC, patrickmann commented on graylog2-server/src/main/java/org/graylog2/migrations/V20241212102900_ScopeMigration.java
> +    public V20241212102900_ScopeMigration(ClusterConfigService configService, MongoCollections mongoCollections) {
Good point - talk about a long-running PR

2025-03-04 08:33 UTC, patrickmann commented on graylog2-server/src/main/java/org/graylog2/migrations/V20241212102900_ScopeMigration.java
> +        updateSystemEventScopes();
Added

2025-03-04 10:10 UTC, kodjo-anipah approved these changes
LGTM

2025-03-04 10:13 UTC, merged