Migrate view sharing to grants
Graylog2/graylog2-server pull request #8707
Opened 2020-08-05 17:20 UTC by mpfz0r

WIP

2020-08-14 11:55 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
> -        final String userName = requireNonNull(currentUser, "currentUser cannot be null").getName();
Since we have a `String` now, I think we should check that the `userName` is not null **and** not empty.

2020-08-14 11:56 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
> +    public GrantDTO create(GrantDTO grantDTO, String userName) {
How about adding a test for this? :slightly_smiling_face:

2020-08-18 10:15 UTC, mpfz0r commented on graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_MigrateRolesToGrantsTest.java
> +public class V20200803120800_MigrateRolesToGrantsTest {
cool! thanks

2020-08-24 14:28 UTC, kmerz requested changes
For some reason not all of my test roles get deleted.

I tried to debug it, but there they get deleted :(

Let's have a look tomorrow together!

2020-08-25 09:36 UTC, kmerz approved these changes
Code looks excellent :heavy_check_mark: 
Works with my :computer: :heavy_check_mark:

2020-08-25 09:37 UTC, merged