Remove shared entities mock from EntityShareStore
Graylog2/graylog2-server pull request #8774
Opened 2020-08-12 07:51 UTC by linuspahl

- Update response structure
- Remove not needed SharedEntitesOverviewItem

This is a draft PR, because I still need to talk with the rest of the team to display the owners correctly.

2020-08-14 08:44 UTC, linuspahl commented on graylog2-web-interface/src/stores/permissions/EntityShareStore.js
> +      // const promise = permissionsMock.searchPaginatedEntitySharesResponse(page, perPage, query, additionalQueries);
I just saw, I forgot to remove this line. If there is nothing else that needs to be adjusted, I will remove it in `feature/permissions`

2020-08-20 08:22 UTC, kmerz requested changes

2020-08-20 08:22 UTC, kmerz commented on graylog2-web-interface/src/logic/permissions/GRN.js
> +      return Routes.pluginRoute('SYSTEM_TEAMS_TEAMID')(id);
Routes.getPluginRoute 

willst du hier verwenden, damit wenn das `enterprise` plugin nicht da ist, kein Fehler geschmissen wird.

2020-08-20 08:22 UTC, kmerz commented on graylog2-web-interface/src/logic/permissions/GRN.test.js
> +    // ${'team'}       | ${'grn::::team:team-id'}            | ${Routes.pluginRoute('SYSTEM_TEAMS_TEAMID')('team-id')}
Team wirst du nicht testen können, da der Test sich nicht darauf verlassen sollte das enterprise da ist.

Sonst kann eine OpenSource User den Test nicht ausführen.

2020-08-20 08:22 UTC, kmerz commented on graylog2-web-interface/src/logic/permissions/GRN.test.js
> +    // ${'dashboard'}  | ${'grn::::dashboard:dashboard-id'}  | ${Routes.pluginRoute('DASHBOARDS_VIEWID')('dashboard-id')}
"Routes.pluginRoute('DASHBOARDS_VIEWID')('dashboard-id')"

gibt es doch gar nicht???

2020-08-20 09:29 UTC, kmerz approved these changes
This is how we do it! :clap: 
Works for me :heavy_check_mark:

2020-08-20 09:29 UTC, merged