slack plugin initial version
Graylog2/graylog2-server pull request #8893
Opened 2020-08-28 23:10 UTC by lingpri

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2020-08-31 16:17 UTC, kyleknighted commented
Could you implement https://graylog2.github.io/frontend-documentation/#!/ColorPicker with the ability to manually add the hex color with a preview of the color?

2020-08-31 16:30 UTC, waab76 commented
Failed while attempting to send a test event during setup:

![Screen Shot 2020-08-31 at 12 29 24 PM](https://user-images.githubusercontent.com/6466251/91743339-a9ca3300-eb85-11ea-970c-fd46ac36860e.png)

2020-08-31 16:31 UTC, waab76 commented
Unable to save Slack notification:

![Screen Shot 2020-08-31 at 12 31 05 PM](https://user-images.githubusercontent.com/6466251/91743487-e4cc6680-eb85-11ea-9def-8d910d3ddad8.png)

2020-09-01 09:07 UTC, bernd requested changes
See inline comments.

Another question: what's the reason for putting this into the server core instead of the integrations plugin?

2020-09-08 17:38 UTC, lingpri commented on graylog2-server/src/main/java/org/graylog/events/notifications/types/SlackClient.java
> +import java.net.*;
@bernd the components for `EmailNotification` exists in the project `graylog2-server`, hence i raised the PR for slack-plugin in `graylog2-server` repository.

2020-09-08 17:42 UTC, lingpri commented on graylog2-server/src/main/java/org/graylog/events/notifications/types/SlackClient.java
> +				final URI proxyUri = new URI(proxyURL);
I will make the changes.

2020-09-08 17:43 UTC, lingpri commented on graylog2-server/src/main/java/org/graylog/events/notifications/types/SlackEventNotification.java
> +		CustomMessageModelData modelData = CustomMessageModelData.builder()
Yeah, I will look into refactoring the code.

2020-09-09 08:18 UTC, bernd commented on graylog2-server/src/main/java/org/graylog/events/notifications/types/SlackClient.java
> +import java.net.*;
@lingpri Please move this PR to the graylog-plugin-integrations repository.

2020-09-17 15:03 UTC, lingpri commented
> Could you implement https://graylog2.github.io/frontend-documentation/#!/ColorPicker with the ability to manually add the hex color with a preview of the color?

@kyleknighted - I forgot, why I need a color picker for the slack plugin. could you please remind me. Also, @bernd has suggested that I move the code to the `graylog-plugin-integrations` project. 

> Could you implement https://graylog2.github.io/frontend-documentation/#!/ColorPicker with the ability to manually add the hex color with a preview of the color?

@kyleknighted - is this for the `notification-color` element in the form?

```
<Input id="notification-color"
               name="color"
               label="Custom Message Color"
               type="text"
               bsStyle={validation.errors.color ? 'error' : null}
               help={lodash.get(validation, 'errors.color[0]', 'Color to use for Slack message')}
               value={config.color || ''}
               onChange={this.handleChange}
               required />
```

2020-09-17 15:41 UTC, kyleknighted commented
@lingpri 
>  I forgot, why I need a color picker for the slack plugin. could you please remind me. 

I do not know the requirements for this plugin, so I am not sure why you need a color. Perhaps @bud1979 or @waab76 know the requirements and why you need color.

>  is this for the notification-color element in the form?

Yes, if the requirements ask for a user provided color, please use the the ColorPicker component.

2020-10-29 21:30 UTC, lingpri commented
1. https://github.com/Graylog2/graylog-plugin-integrations/pull/618
2. https://github.com/Graylog2/graylog-plugin-integrations/pull/595

2020-10-29 21:31 UTC, lingpri commented
the initial version is in plugin integrations branch .

2020-10-29 21:31 UTC, closed without merging