Run local production server
Graylog2/graylog2-server pull request #8980
Opened 2020-09-16 13:32 UTC by Gaya

Allows the user to run a local version of the production server.

## Description

Run a local version of production which communicates through the API provided by Docker.

## Motivation and Context

In order to test production builds locally we have to spin up a local server which can serve assets to the browser. This was not possible before, but with these changes you can! All you need is the Docker running in dev mode and it will be available to use in this local production build.

## How Has This Been Tested?

By running the local server commands.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2020-09-28 08:11 UTC, dennisoelkers requested changes
Looks good so far, great work! Just one minor request.

2020-09-28 08:16 UTC, Gaya commented on graylog2-web-interface/runProductionLocal.js
> +  productionHelpers.config('http://localhost:9000/api'),
Yeah, good idea, will change

2020-10-20 07:17 UTC, Gaya commented
@dennisoelkers did you get the chance to look at this one? I want to use it for testing in `cloud` too

2023-10-04 07:59 UTC, closed without merging

2023-10-04 07:59 UTC, dennisoelkers commented
Not requested again, closing it for now.