Avoid URL synchronization if view is not currently dirty.
Graylog2/graylog2-server pull request #8995
Opened 2020-09-18 08:57 UTC by dennisoelkers

## Description

## Motivation and Context

Before this change, the URL synchronization hook unconditionally added
query/timerange/streams information to the current URL if the current
view is a search (and not a dashboard). This lead to an unnecessary URL
change if a saved search is loaded (as the persisted
query/timerange/streams are identical to the current state).

This change is checking if the current view is dirty. If not, no change
is made.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

2020-09-22 13:49 UTC, linuspahl requested changes
I found one problem which occurs when using the browser navigation:
![search-example](https://user-images.githubusercontent.com/46300478/93890796-02a36c00-fceb-11ea-9533-86293f7694b0.gif)

If a user changes his search multiple times, he can still go back to a previous state by using the bowser navigation, but he will never get back to the initial state. (If he did not executed the first search manually). It behaves the same way for saved searches and streams.

2020-09-22 14:44 UTC, kyleknighted approved these changes
Couple notes, but LGTM

2020-09-22 14:44 UTC, kyleknighted commented on graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
> +  const { view, dirty } = ViewStore.getInitialState() || {};
I do not think there is a way for `ViewStore.getInitialState()` to return falsy, so we may not need the fallback `|| {}`

```suggestion
  const { view, dirty } = ViewStore.getInitialState();
```

2020-09-22 14:44 UTC, kyleknighted commented on graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
> +  if (view && view.type === View.Type.Search && dirty) {
As noted in a DM, optional chaining was not available when this was initially written, but could be simplified a little bit with 
```suggestion
  if (view?.type === View.Type.Search && dirty) {
```

2020-09-28 12:50 UTC, dennisoelkers commented
Closing this, as it is not a proper solution, as [pointed out](https://github.com/Graylog2/graylog2-server/pull/8995#pullrequestreview-493480066) by @linuspahl

2020-09-28 12:50 UTC, closed without merging