Add startpage to the Settings Section of a user
Graylog2/graylog2-server pull request #9444
Opened 2020-11-11 13:11 UTC by kmerz

## Motivation
Prior to this change, there was no way to reset the start page of a
user. A user could only change the startpage to a different stream.

## Description
This change will add a new field to the settings section of a user where
he can edit its startpage.

This is the beginning of a solution for `4.1`

Refs #9443

2020-11-13 09:21 UTC, linuspahl requested changes
Just found a `console.log`, otherwise it looks good!

2020-11-13 09:21 UTC, linuspahl commented on graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
> +  console.log(data);
`console.log`

2020-11-26 11:17 UTC, linuspahl requested changes
Looks good so far, just added some suggestions.

One fundamental thing I realized, the settings section is only visible for admins, we should probably just hide all settings except the start page field.

2020-12-03 11:49 UTC, kmerz commented
> Looks good so far, just added some suggestions.
> 
> One fundamental thing I realized, the settings section is only visible for admins, we should probably just hide all settings except the start page field.

2020-12-03 13:52 UTC, kmerz commented on graylog2-web-interface/src/components/users/StartpageFormGroup.tsx
> +    <Field name="startpage">
There is no harm in only selecting a type and I think it is clear that no start page is selected then. So I would not add a validation.

2020-12-03 13:54 UTC, kmerz commented on graylog2-web-interface/src/components/users/StartpageFormGroup.tsx
> +        }).then(({ list }) => setStreams(list.map(_grnOptionFormatter).toArray())));
On request is overriding the other and we and up only having either streams or dashboards but not both :confused: So we need to synchronize the requests

2020-12-03 16:59 UTC, kmerz commented
/rebase

2020-12-04 15:32 UTC, linuspahl requested changes
Looks like there is a failing test.

2020-12-04 15:32 UTC, linuspahl commented on graylog2-web-interface/src/components/users/StartpageFormGroup.tsx
> +                               placeholder={`Select ${value?.type}`}
When there is no type selected it says `Select undefined`. 
Let use `Select ${value?.type} ?? 'entity'` here.

2020-12-07 17:12 UTC, linuspahl approved these changes
Looks good to me!

2020-12-07 17:12 UTC, merged