Hide inputs and related on cloud
Graylog2/graylog2-server pull request #9537
Opened 2020-11-18 13:24 UTC by Gaya

Inputs on cloud will be managed through forwarders instead of `system/inputs`

Hide / disable features that allow access to these parts on cloud.

## Motivation and Context

Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/99

## How Has This Been Tested?
Tested in the cloud environment

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

## To do:
- [ ] Disable inputs page and navigation
- [ ] Solve notifications
- [ ] Node Inputs
- [ ] Input extractors

External:
- [ ] Solve cloudwatch
- [ ] Solve 0365

2020-11-18 19:47 UTC, Gaya commented
@edmundoa this one is ready without the o365 and cloudwatch disabling. I think it's best to wait until cloud 4.0 lands until we handle those two case. I have two pending PRs open for it... but they need to be updated accordingly.

2020-11-20 13:01 UTC, edmundoa requested changes
This is looking quite good already. Besides the changed files, I think we are only missing one place in the UI where you can go to Inputs/Extractors:

![Screen Recording 2020-11-20 at 13 33 02](https://user-images.githubusercontent.com/716185/99801464-5d641300-2b36-11eb-8d52-b50b019fb49d.gif)

2020-11-23 06:34 UTC, Gaya commented on graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx
> +              </HideOnCloud>
Good catch!

2020-11-23 08:13 UTC, Gaya commented
> This is looking quite good already. Besides the changed files, I think we are only missing one place in the UI where you can go to Inputs/Extractors:

@edmundoa thanks! Didn't know about this one. Made another thing to filter it like we do the menu items.

2020-11-25 11:20 UTC, edmundoa approved these changes
Looks good to me :shipit:

2020-11-25 11:20 UTC, merged