Migrating views components to TypeScript.
Graylog2/graylog2-server pull request #9561
Opened 2020-11-20 11:21 UTC by dennisoelkers

## Description

## Motivation and Context

This PR is migrating all remaining views components to TypeScript.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2020-11-23 14:32 UTC, linuspahl commented on graylog2-web-interface/src/views/components/DebugOverlay.tsx
> -
Why did you remove the prop types here? The import still exists.

2020-11-23 14:32 UTC, linuspahl commented on graylog2-web-interface/src/views/components/DebugOverlay.tsx
> +import View from '../logic/views/View';
This import is not needed.

2020-11-23 14:35 UTC, linuspahl commented on graylog2-web-interface/src/views/components/Field.tsx
> +  menuContainer?: HTMLElement,
Even though the prop is optional, shouldn't this be `HTMLElement | null | undefined`?

2020-11-23 14:38 UTC, linuspahl commented on graylog2-web-interface/src/views/components/QueryBar.tsx
> +  },
What about `viewMetadata: ViewMetadata`?

2020-11-23 15:43 UTC, linuspahl requested changes
Looks good to me, just found some smaller things which can be improved.

2020-11-23 15:43 UTC, linuspahl commented on graylog2-web-interface/src/views/components/widgets/FieldSelect.tsx
> +  inputId?: string,
Looks like these two need some default props.

2020-11-23 15:43 UTC, linuspahl commented on graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.tsx
>  import withParams from 'routing/withParams';
This import can be removed

2020-11-23 15:43 UTC, linuspahl commented on graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
> +  sections?: Array<SidebarSection>,
These props have no corresponding `defaultProps` declaration.

2020-11-23 15:43 UTC, linuspahl commented on graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.tsx
>    // $FlowFixMe: type is always defined
This `// $FlowFixMe:` can be removed

2020-11-24 09:06 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/DebugOverlay.tsx
> -
We cannot get these in sync with the types of prop (`object` vs. `ViewStoreState`), so I removed them, as we do not rely on them for this debug component. I removed the import though.

2020-11-24 09:10 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/QueryBar.tsx
> +  },
:white_check_mark:

2020-11-24 09:12 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.tsx
> +  children: React.ReactElement,
:white_check_mark:

2020-11-24 09:16 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/messagelist/HighlightMessageInQuery.tsx
> +  query?: any,
:white_check_mark:  (I added it to support a test, but the prop is not used in that component it all, so I moved it to the test.)

2020-11-24 09:17 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/widgets/FieldSelect.tsx
> +  inputId?: string,
:white_check_mark:

2020-11-24 09:18 UTC, dennisoelkers commented on graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.tsx
>  import withParams from 'routing/withParams';
:white_check_mark:

2020-11-24 09:23 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
> +  sections?: Array<SidebarSection>,
:white_check_mark:

2020-11-24 09:23 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.tsx
>    // $FlowFixMe: type is always defined
:white_check_mark:

2020-11-24 09:29 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/messagelist/MessageField.tsx
> +  }).isRequired,
We need to use `exact` in most cases as TS's objects are always exact. I completed the definition and added a `Message` custom prop type that we can reuse.

2020-11-24 11:39 UTC, linuspahl approved these changes
Look good to me!

2020-11-24 13:21 UTC, merged