Improving `connect` type inference regarding `PropTypes` and `defaultProps`
Graylog2/graylog2-server pull request #9721
Opened 2020-12-08 11:15 UTC by linuspahl

## Description
This PR improves the type inference when using `connect` for a component which also uses `defaultProps`.  Previously we had a  problem when using connect in the following case:

Component has a prop `exampleProp`. This prop is defined as required in the component `Prop` type, but has a default value. Since it has a default value, the `PropType`s are defining the prop as optional. When we use this component the `exampleProp` is required. With this the `exampleProp` is types as optional.

There is still one case were we do not infer the props perfectly. If the mentioned `exampleProp` is an object and the TypeScript type defines its values as required, we can't define a PropType definition which defines as the prop optional, but the attributes are required. With the current inference all attributes are types as optional.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2020-12-09 12:37 UTC, dennisoelkers requested changes
Looks good, some nice changes in there! Added some remarks/questions inline.

2020-12-09 12:37 UTC, dennisoelkers commented on graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
> -    urlType: PropTypes.string,
We can do this instead:

```
    urlType: PropTypes.oneOf(['regex', 'literal', ''] as const),
```

2020-12-09 12:37 UTC, dennisoelkers commented on graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
> -    currentUser: PropTypes.object.isRequired,
We can do this instead:

```
    currentUser: PropTypes.exact({
      permissions: PropTypes.arrayOf(PropTypes.string),
    }).isRequired,
```

2020-12-09 12:37 UTC, dennisoelkers commented on graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
> +    // eslint-disable-next-line react/default-props-match-prop-types
If we use the suggestion above, we can remove this.

2020-12-09 12:37 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/widgets/Widget.tsx
> -    view: PropTypes.object.isRequired,
I think we might be able to use CustomPropTypes.CurrentView` here.

2020-12-09 12:37 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/widgets/Widget.tsx
> -    widget: PropTypes.shape({
Can we use `PropTypes.instanceOf(WidgetModel)` here?

2020-12-09 12:37 UTC, dennisoelkers commented on graylog2-web-interface/src/views/components/widgets/Widget.tsx
> -    position: PropTypes.object.isRequired,
Can we use `PropTypes.instanceOf(WidgetPosition)` here?

2020-12-09 16:06 UTC, linuspahl commented
@dennisoelkers Thanks for the good feedback! I wrongly assumed `instanceOf` is not working as expected in the mentioned cases, due to a failing test. But I just had to update the test properly.

2020-12-10 12:18 UTC, dennisoelkers approved these changes
Good work!

2020-12-10 12:18 UTC, merged