Custom chart legend
Graylog2/graylog2-server pull request #9844
Opened 2020-12-22 16:33 UTC by kmerz

## Description
Provide value action in the legend of a chart.

## Motivation and Context
Make charts more interactive.

## Screenshots (if appropriate):
![value-actions-in-chart](https://user-images.githubusercontent.com/448763/102911040-ce6f5100-447b-11eb-8c90-5cd0cbbfd80b.gif)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-02-01 09:25 UTC, dennisoelkers requested changes
I am seeing some regressions with the color picker popover:
![image](https://user-images.githubusercontent.com/41929/106439130-a2ca8800-6477-11eb-9fe6-76d386970662.png)
And it is now by default going out of bounds for the default histogram's legend:
![image](https://user-images.githubusercontent.com/41929/106439263-c7befb00-6477-11eb-91bb-c989d5b02378.png)

2021-02-08 16:16 UTC, dennisoelkers requested changes
The legend of a pie chart is cut off for me in edit mode:

![image](https://user-images.githubusercontent.com/41929/107247280-637cd800-6a31-11eb-814b-073450e1bfee.png)

2021-02-12 15:20 UTC, dennisoelkers approved these changes

2021-02-12 15:20 UTC, merged

2021-02-12 16:19 UTC, aim4r commented
This looks awesome, thanks for implementing it !