Do not allow selecting same pipeline stage twice
Graylog2/graylog2-server pull request #9911
Opened 2021-01-14 16:35 UTC by edmundoa

Before this change, it was possible to add or edit a pipeline stage using the same number as an existing one, resulting in one of the stages silently disappearing. This PR adds validation for the stage and displays an error indicating the situation where the number selected is already used.

While working on the fix, I realised most pipeline components are in need of some care, so I started modernizing those I wanted to edit to fix the issue, but I ended up doing that for the whole folder. Changes there include moving files to Typescript, adding some type definitions, replacing `createReactClass` and class components with functional components, and switching to styled-components. I know this obscures the fix and makes it harder to check the PR, but I think we will still get some good value out of it. From my perspective it's fine checking if the pages work overall, and if [the fix](https://github.com/Graylog2/graylog2-server/commit/415f3a1f78389a2e73134678cdabaf34ec1fd94c) is working as expected.

Since many of the changes are exclusively for master, I will prepare a basic fix that we can backport to 4.0.

Fixes #6806

2021-01-14 16:49 UTC, edmundoa commented
It seems that my linter was not checking all rules I thought it was using, will take another look.

2021-01-15 11:55 UTC, ousmaneo requested changes
Thank you for working on this @edmundoa.
I tested and reviewed the fix and it works great. And had a look at the modernization changes and it looks good too. Only one small thing inline.

2021-01-15 11:55 UTC, ousmaneo commented on graylog2-web-interface/src/components/pipelines/PipelineDetails.tsx
> +          <PipelineDl className="dl-horizontal" style={{ marginTop: 10 }}>
I think this style can go to the styled-component

2021-01-15 13:28 UTC, ousmaneo approved these changes
Legit

2021-01-15 13:29 UTC, merged