Enabling configuration of new relative time range type with properties `from` and `to` in date time picker.
Graylog2/graylog2-server pull request #9946
Opened 2021-01-21 13:53 UTC by linuspahl

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-01-21 18:16 UTC, kyleknighted commented on graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeRangeSelect.tsx
> +                     title="Set the range value"
```suggestion
                     title={`Set the ${fieldName} value`}
```

2021-01-25 19:02 UTC, kyleknighted commented
![image](https://user-images.githubusercontent.com/122591/105752974-94c3b700-5f0d-11eb-8d46-b71c843ac04f.png)

Needs validation for the limitDuration

2021-01-25 19:05 UTC, kyleknighted commented
![image](https://user-images.githubusercontent.com/122591/105753214-eec47c80-5f0d-11eb-8985-9fe8b89c56a1.png)

I keep clicking submit but the dirty flag never goes away and the URL does not update

2021-01-25 19:05 UTC, kyleknighted requested changes
left a couple comments

2021-02-01 18:40 UTC, kyleknighted commented
If I set an offset, then submit the form, the URL updates as expected.
But when I open the Date Picker again and change to Absolute tab, the dates are not properly converting so there is an error on the default date. 
Then switching back to Relative tab it goes back to the default 5 minutes instead of the date that is currently set with the offset.

Some tab changing logic probably just needs a little care on migrating the date.

2021-02-02 17:09 UTC, linuspahl commented
@kyleknighted  I can't reproduce the migration error when changing tabs (relative -> absolute). Can we have a look together?

![dtp-migration](https://user-images.githubusercontent.com/46300478/106635490-2e7c0b80-6581-11eb-8604-c0e1c376c824.gif)

Regarding "Switching back to Relative tab it goes back to the default 5 minutes instead of the date that is currently set with the offset." As far as I know we never considered the initial time range in the migration strategies in `TimeRangeForForm`, but I agree that it would be a benefit in most cases. Before we implement this change, let's talk about the different scenarios and how to deal with them.

2021-02-03 13:00 UTC, kyleknighted commented
@linus you're correct, sorry, I was not thinking clearly on what `migrateTimeRangeToNewType` is doing. Ready to merge once the conflicts are resolved

2021-02-03 13:27 UTC, kyleknighted approved these changes

2021-02-03 13:28 UTC, merged